### ISSUE TITLE
The Block Storage "Profiles" page needs to document minimum IOPS per profile

### ISSUE THREAD

**Issue by eniopineda** [ibm-cloud-docs/vpc#1]
This is the documentation page: https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-profiles

The documentation needs to state what the minimum IOPS are for each tier. On VPC Gen2 they are as follows:
* For volumes created using a "tiered" profile (**10iops-tier**, **5iops-tier**, **general-purpose**) the minimum IOPS is 3000.
* For volumes created using the **custom** profile the requested IOPS are honored - as long as they're valid for the profile.

This causes confusion as it is not clearly stated what the minimum IOPS are. A customer creating a 200GB volume at the 5iops-tier expects to see 1000 IOPS, but instead sees 3000. That's OK, but it should be documented.

**Comment by stemke** [comment]
Hi @eniopineda - Thank you for your feedback. The team is investigating and will make any appropriate updates.  We appreciate your contributions and input.  Thanks!

**Comment by eniopineda** [comment]
I ended up opening an internal issue for this.
Documentation changes are being worked under that issue.
