### ISSUE TITLE
Document how to create an alert like "notify me when I'm using 75% of my VPC quota"

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-docs/vpc#100]
when creating an alert for quota in Monitoring, you have only two option, the current value (consumption) and the limit:

![image](https://user-images.githubusercontent.com/12746550/151608587-f4bedf08-5488-40ab-aa8a-993f720b5918.png)

But consumption is the absolute value (3 vpcs).

However I'd like to create an alert that notifies me when 75% of my usage is reached for any VPC quota. This seems to be feasible using a complex SysDig formula like the one used by the quota dashboard:

![image](https://user-images.githubusercontent.com/12746550/151608775-6d029bfb-b07f-4ac1-bc19-fbb6b49b77c4.png)

An example would be better and likely a common ask

**Comment by amatetic** [comment]
thanks for your feedback on the Quotas content. We'll take a closer look at your comments in upcoming sprints.

**Comment by gudrun-wolfgram** [comment]
Tracking issue internally
