### ISSUE TITLE
Group quota topics under a common umbrella

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-docs/vpc#101]
1. https://cloud.ibm.com/docs/vpc?topic=vpc-quotas
2. https://cloud.ibm.com/docs/vpc?topic=vpc-vpc-quota-metrics and
3. https://cloud.ibm.com/docs/vpc?topic=vpc-quota-metrics-dashboard-troubleshooting

➡️  all talk about the VPC quotas but are in 3 different places in the doc.

A common topic/story about quotas would make more sense. Also there are not linked together 1. does not point to 2. or 3.

![image](https://user-images.githubusercontent.com/12746550/151609349-f57c027b-170f-4643-be25-937693151960.png)

**Comment by gudrun-wolfgram** [comment]
@l2fprod - thanks for your feedback on the Quotas content. We'll take a closer look at your comments in upcoming sprints.

**Comment by gudrun-wolfgram** [comment]
Tracking issue internally.
