### ISSUE TITLE
Give more context about what are these quotas and where I will find them

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-docs/vpc#102]
https://cloud.ibm.com/docs/vpc?topic=vpc-vpc-quota-metrics#quota-metrics-available-by-resource-type

This page does not give any context about quotas. Is there a single place in IBM Cloud console where I can see all my quotas? Am I supposed to know where to look for these metrics? No words about IBM Cloud monitoring and the dashboard.

The page gives definitions and attributes but lacks any content or example.

**Comment by gudrun-wolfgram** [comment]
Tracking issue internally.
