### ISSUE TITLE
Troubleshooting quota dashboard page could be merged with the definition of the metrics and include an intro on the dashboard

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-docs/vpc#103]
https://cloud.ibm.com/docs/vpc?topic=vpc-quota-metrics-dashboard-troubleshooting goes me really worried about the quota dashboard. Why is the only doc about this dashboard a troubleshooting guide?

We could include this troubleshooting as a note in the monitoring / metrics page and put more description about the dashboard itself

![image](https://user-images.githubusercontent.com/12746550/151615670-b5437799-b58d-462b-9d22-1363e099f6ed.png)

**Comment by gudrun-wolfgram** [comment]
Tracking issue internally.
