### ISSUE TITLE
Metadata service is no longer enabled by default, 

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/vpc#104]
The documentation stats in various places that the metadata service is enabled, by default, however that is no longer the case.  Can the docs be updated? 

https://cloud.ibm.com/docs/vpc?topic=vpc-imd-configure-service&interface=ui#imd-enable-new-instance-ui

**Comment by gudrun-wolfgram** [comment]
@dprosper - thanks for your feedback. The content is updated to reflect the default behavior.
