### ISSUE TITLE
Quota for Dedicated Host Groups is not documented - Try #2

### ISSUE THREAD

**Issue by eniopineda** [ibm-cloud-docs/vpc#106]
See https://github.com/ibm-cloud-docs/vpc/issues/97. That issue was closed by @gudrun-wolfgram incorrectly, in my opinion.

There is a quota/limit enforced for **_Dedicated Host Groups_** per region per account, but that limit is not documented in the Quotas and service limits (https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#vpcquotas) nor the documentation for Dedicated Hosts.

Limits and quotas are OK but they need to be documented.
There is an error message indicating the quota has been hit, but there is no documentation anywhere stating what the quota/limit is.
```
04:39:02 ERROR: Request  POST :  /v1/dedicated_hosts?version=2022-01-20&generation=2  response status_code:  400  res: <Response [400]>
04:39:02     *** over_quota -- Allocating a dedicated group will put user over quota. Allocated: 100, Quota: 100
```
I'm not asking about Dedicated Hosts. I am asking about Dedicated Host **Groups**.

Maybe it should be documented under "Service Limits" since it appears the **Dedicated Host Group** limit can't be adjusted. All I'm saying is that the limit should be documented.

**Comment by amatetic** [comment]
There is currently a jira item that Keith is working on that is a duplicate of this github issue. I am assigning the issue to Keith and i have update his jira item with this github issue.

**Comment by eniopineda** [comment]
I opened the that JIRA. Don't need 2 issues open. Closing this one.
