### ISSUE TITLE
This documentation appears to be out of date

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/vpc#108]
The article was last updated in August 2021.  The "Important" statement that data logging integration is being upgraded and won't be available in all relevant regions until it's done.  There was no ETA on that but we suspect that upgrade is long completed.

The article also appears to not list all the regions in which this can be done now, as of March 2022.

**Comment by Lauren-Fulcher** [comment]
Searched VPC repo for "data logging," "data logging integration," and "integration," but found nothing close to this statement. Must have already been deleted.
