### ISSUE TITLE
Deleting a Floating IP: Validate documentation against functionality

### ISSUE THREAD

**Issue by JCalabuig** [ibm-cloud-docs/vpc#11]
Documentation states: 
If the floating IP is bound to a public gateway or instance, the link must be deleted (released) before the floating IP can be deleted.
Tested behaviour in the UI: 
- It is not possible to disassociate a Floating IP from a public gateway
- It is possible to release a Floating IP that is attached to an instance
Please check

**Comment by depst** [comment]
Fixed on staging
