### ISSUE TITLE
Broken link in https://cloud.ibm.com/docs/vpc?topic=vpc-end-to-end-private-connectivity&interface=cli#provisioning_private_lb

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-docs/vpc#112]
HI, in the page https://cloud.ibm.com/docs/vpc?topic=vpc-end-to-end-private-connectivity&interface=cli#provisioning_private_lb

"Create a private load balancer within your VPC. The IBM Cloud console prevents you from adding the IP of the VPE as a back-end endpoint so use the API or Terraform as an alternative (see [Example Terraform configuration](https://cloud.ibm.com/docs/vpc?topic=vpc-end-to-end-private-dl#example-terraform-configuration))."

The correct link is https://cloud.ibm.com/docs/vpc?topic=vpc-end-to-end-private-connectivity&interface=cli#example-terraform-configuration

**Comment by austinmama** [comment]
@jxadro  Thank you!  Just fixed.  Will take about 30 minutes to be visible.
