### ISSUE TITLE
Security Group Resources for Terraform link is broken

### ISSUE THREAD

**Issue by pltrent** [ibm-cloud-docs/vpc#115]
In the About Security Groups page (https://cloud.ibm.com/docs/vpc?topic=vpc-using-security-groups), the link for
"https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#sec-group" is broken.

**Comment by austinmama** [comment]
Thank you for your feedback.  The link was corrected and now points to the Terraform registry.  You can also find a complete list of VPC infrastructure resources at https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-resources-datasource-list#vpc-infrastructure_rd
