### ISSUE TITLE
About Security Groups broken link

### ISSUE THREAD

**Issue by Brenne** [ibm-cloud-docs/vpc#116]
I'd like to report a broken link.
Page:
https://cloud.ibm.com/docs/vpc?topic=vpc-using-security-groups

Pragraph: _Related links_

The link _Security Groups for VPC infrastructure resources for Terraform_ leads to an error page.

**Comment by Brenne** [comment]
closing since this is a duplicate to #115

**Comment by austinmama** [comment]
Fixed this link. Thank you @Brenne - Appreciate the feedback!

https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-resources-datasource-list#vpc-infrastructure_rd
