### ISSUE TITLE
Volume Naming Convention Not Accurate

### ISSUE THREAD

**Issue by luispineda1** [ibm-cloud-docs/vpc#118]
the below document states the below

https://cloud.ibm.com/docs/vpc?topic=vpc-viewing-block-storage&interface=ui

the doc states the below

_Volume names must be unique across the entire VPC infrastructure._

upon checking with RSOS, it appears that this statement is not accurate

https://ibm-cloudplatform.slack.com/archives/C9L8GBP16/p1652518477923579?thread_ts=1652152532.651029&cid=C9L8GBP16

This doc needs to be updated to reflect what is actually correct as "entire VPC infrastructure" should mean irregardless of account/vpc/region

**Comment by vickmuir** [comment]
This issue has been resolved. The update is to be visible in few minutes.
