### ISSUE TITLE
Difficult to find in the docs: Cloud Service Endpoint source addresses

### ISSUE THREAD

**Issue by powellquiring** [ibm-cloud-docs/vpc#12]
![image](https://user-images.githubusercontent.com/6932057/98588196-23feee00-2280-11eb-981a-32171362ea58.png)

I don't think it is on the first page of search

![image](https://user-images.githubusercontent.com/6932057/98588168-18abc280-2280-11eb-8185-aafc6645604a.png)

**Comment by gudrun-wolfgram** [comment]
Opened an internal issue to address this.
