### ISSUE TITLE
Security Groups can be used on VPE. Please fix the limitation page.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#120]
Hello,

On this limitation page, it says Security Groups are not supported on VPE.
https://cloud.ibm.com/docs/vpc?topic=vpc-limitations-vpe

But we can configure Security Groups on VPE now.
https://cloud.ibm.com/docs/vpc?topic=vpc-configure-acls-sgs-endpoint-gateways

Could you fix the limitation page?
Thank you,

**Comment by austinmama** [comment]
Updated topic. Closing.  Thank you.
