### ISSUE TITLE
Use Secret Manager instead of IBM Cloud Certificate Manager in the docs

### ISSUE THREAD

**Issue by rajatagarwal** [ibm-cloud-docs/vpc#123]
It appears that the IBM Cloud Certificate Manager service is going to deprecate on 30th September 2022. I'd say to update the documentation to use Secret Manager instead on this [page](https://cloud.ibm.com/docs/vpc?topic=vpc-client-to-site-vpn-planning#server-authentication). 

Info on deprecation of IBM Cloud Certificate Manager: https://cloud.ibm.com/apidocs/certificate-manager

**Comment by austinmama** [comment]
Secrets Mgr support rolled out on 7/7.  Closing.
