### ISSUE TITLE
Pricing Link wrong

### ISSUE THREAD

**Issue by bbogaert67** [ibm-cloud-docs/vpc#124]
The pricing link on the left menu bar goes to "[IBM Cloud Virtual Servers for Classic Infrastructure](https://www.ibm.com/cloud/virtual-servers)" => CLASSIC ! Not VPC!
Unable to find back the costs for VPN, LB, Egress, etc. !

**Comment by gudrun-wolfgram** [comment]
@bbogaert67 - thanks for your feedback! I'm not able to reproduce the issue that you're seeing. 

From the VPC repository https://cloud.ibm.com/docs/vpc, the Pricing link in the left-hand navigation goes here: https://www.ibm.com/cloud/vpc/pricing

Please let me know if the problem persists for you.
