### ISSUE TITLE
VPC BYOK:  Managing data encryption incorrectly states data volumes are detached

### ISSUE THREAD

**Issue by jjfall** [ibm-cloud-docs/vpc#125]
In the section [User actions that impact root key states and resource status](https://cloud.ibm.com/docs/vpc?topic=vpc-vpc-encryption-managing&interface=ui#byok-root-key-states), on the "Delete root key" tab, the documentation states that "data volumes are detached" which is incorrect.  The instance is powered off but the data volume attachment is retained.  This design was chosen so that if the customer root key is restored, the instance can be powered on and resumes as it was prior to key deletion.

To summarize the recommended change, in the data volume row this should say:

"If the data volume is attached to a running instance that instance is stopped. Standalone data volumes cannot be attached to instances. You can delete the volume."

Also, a boot volume can only be attached to a single instance so the boot volume row should refer to a single instance:

"The associated virtual server instance is stopped. A stopped instance cannot be started while the instance boot volume is in _unusable_ state."

There is also a section on [deleting root keys](https://cloud.ibm.com/docs/vpc?topic=vpc-vpc-encryption-managing&interface=ui#byok-delete-root-keys).  Bullet 2 should say:

* _If the deleted root key is protecting data volumes, the associated virtual server instance is stopped._

![image](https://user-images.githubusercontent.com/99987300/179564045-938f7534-0a93-46ba-8b59-1da5baecc190.png)

![image](https://user-images.githubusercontent.com/99987300/179563823-bdcb75c4-d399-4cfd-b21c-f355675ce3f2.png)

**Comment by gudrun-wolfgram** [comment]
Thanks @jjfall for your feedback. I'm routing this issue to @donslovenkai .

**Comment by donslovenkai** [comment]
Revised the sections as directed in *staging*. Please review:

https://test.cloud.ibm.com/docs/vpc?topic=vpc-vpc-encryption-managing&interface=ui#byok-root-key-states
https://test.cloud.ibm.com/docs/vpc?topic=vpc-vpc-encryption-managing&interface=ui#byok-delete-root-keys

**Comment by jjfall** [comment]
Looks great @donslovenkai.  Thank you!

cc:  @rodrabe

**Comment by donslovenkai** [comment]
Published. Thank you.

https://cloud.ibm.com/docs/vpc?topic=vpc-vpc-encryption-managing&interface=ui
