### ISSUE TITLE
Could you provide EOS information on IBM Cloud for RHEL8.5 and later?

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#126]
Hello,
I am referring to the following URLs regarding EOS of RHEL. Could you provide EOS information for RHEL8.5 and later?

VPC
https://cloud.ibm.com/docs/vpc?topic=vpc-guest-os-lifecycle#rhel

In particular, according to [Red Hat's site](https://access.redhat.com/ja/support/policy/updates/errata), RHEL8.5 is a release provided without Extended Update Support, so I think its EOS date has already passed.
Thank you,

**Comment by gudrun-wolfgram** [comment]
Thank you for your feedback! Currently odd releases are not supported in VPC. The page is now updated for RHEL 8.6.
