### ISSUE TITLE
Broken link on Connecting to Linux instances page

### ISSUE THREAD

**Issue by profhun** [ibm-cloud-docs/vpc#128]
Hi,

On the following page: https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_linux
The link inside the following block is broken.
![Screenshot from 2022-07-28 13-39-50](https://user-images.githubusercontent.com/6312594/181496540-94c0a615-242d-4927-a966-1421106f5e50.png)
[Creating an instance by using the CLI](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-virtual-servers-cli#create-instance-cli)

![Screenshot from 2022-07-28 13-40-45](https://user-images.githubusercontent.com/6312594/181496651-b59a6e50-5883-4e46-bbce-7fbd09350713.png)

Thank you!

**Comment by gudrun-wolfgram** [comment]
@profhun - Thanks for reporting the broken link! It is now updated.
