### ISSUE TITLE
Step 3.2 insufficient documented - Creating a Linux custom image 

### ISSUE THREAD

**Issue by ajendrosch2** [ibm-cloud-docs/vpc#129]
It is not possible to follow the documentation for certain Linux custom images.

For the case of the latest Kali Linux image step 3.2
`lsinitrd /boot/initramfs-$(uname -r).img | grep virtio`
is not possible, since only `/boot/initrd-$(uname -r)` is present.

**Comment by ThomasUllrich666** [comment]
right /boot/initramfs-$(uname -r).img isn't there. Kali Linux based on Debian

**Comment by gudrun-wolfgram** [comment]
Thanks for your feedback on this content. https://cloud.ibm.com/docs/vpc?topic=vpc-create-linux-custom-image&interface=ui#virtio-drivers We'll plan to check into it.

**Comment by amatetic** [comment]
I researched the issue and an update has been made and published: https://cloud.ibm.com/docs/vpc?topic=vpc-create-linux-custom-image#virtio-drivers
