### ISSUE TITLE
Changes/additions to the Managing network interfaces web document

### ISSUE THREAD

**Issue by verdecal** [ibm-cloud-docs/vpc#13]
There are a few things that I think we should add to avoid confusion for other customers.

1. We should add a message or note on the vpc page that if you attach multiple vnics to a VSI, you will have to configure custom routes for all additional vnics beyond the default vnic.

2. On this page, we should have a heading level statement that you need to configure custom routes for all additional vnics, right above the custom route example.

3.  Because we are IBM, we should add centOS and RHEL to the line under Configuring a virtual server instance with multiple interfaces that starts, "You can solve this problem on a Linux platform such as Ubuntu..." and replace it with You can solve this problem on a Linux platform such as Ubuntu, centOS, or RHEL...".  If nothing else, we should neutrally support RHEL flavors.

4. The last thing that I think we should add is an example of how to test the custom routes after you have put them in place.  If anyone is like me, it is easy to make a typo in the static routes or the file based approach.  Adding a short section on using tcpdump and ping will likely save a lot of ticket requests when ping doesn't work as expected.

I have added these comments on behalf of Derren Dunn (dunnderr@us.ibm.com)
My email is jamie.e.de.domenico@ibm.com

**Comment by gudrun-wolfgram** [comment]
Opened an internal issue to address this.
