### ISSUE TITLE
Deleting a VPC using the IBM Cloud console - delete instances

### ISSUE THREAD

**Issue by JCalabuig** [ibm-cloud-docs/vpc#13]
Step 3 

> Delete any resources that are attached to the subnet. In the navigation pane, click Attached resources. **Select each attached instance to go its details page and click the delete icon**.

Issue: When you open the instance details page the delete icon is not available. It is required to click the Stop icon and once the instance is stopped, the delete icon becomes available. So it is required to modify the text in Step 3

**Comment by EliahuBen-Reuven** [comment]
Added this line to step 3: "Attached instances must be stopped before you can delete them."
