### ISSUE TITLE
Needs updating to Secrets Manager from Certificate Manager

### ISSUE THREAD

**Issue by rich-ehrhardt** [ibm-cloud-docs/vpc#130]
Per the announcement [here](https://cloud.ibm.com/docs/certificate-manager?topic=certificate-manager-release-notes#certificate-manager-feb1022), IBM Cloud certificate manager is has been deprecated and is being replaced by Secrets Manager. This document does not describe how to configure a VPN server using secrets manager.

**Comment by austinmama** [comment]
@rich-ehrhardt  Hi Rich.  Can you tell me which topic doesn't describe creating a VPN server w/ Secrets Manager?  This functionality was published July 7th.  Thank you!

**Comment by rich-ehrhardt** [comment]
Hi,
It is one the Creating a VPN server page. The linked page does describe both options, but the link description states “certificate manager” instead of “secrets manager”.

https://cloud.ibm.com/docs/vpc?topic=vpc-vpn-create-server&interface=api

***@***.***

Rich Ehrhardt
Principal Cloud Engineer
IBM Ecosystem Engineering
Worldwide Ecosystems
+61 419 206 724 Mobile
***@***.******@***.***>

IBM

From: austinmama ***@***.***>
Date: Friday, 12 August 2022 at 14:29
To: ibm-cloud-docs/vpc ***@***.***>
Cc: Richard Ehrhardt ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/vpc] Needs updating to Secrets Manager from Certificate Manager (Issue #130)
@rich-ehrhardt Hi Rich. Can you tell me which topic doesn't describe creating a VPN server w/ Secrets Manager? This functionality was published July 7th. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

@rich-ehrhardt<https://github.com/rich-ehrhardt> Hi Rich. Can you tell me which topic doesn't describe creating a VPN server w/ Secrets Manager? This functionality was published July 7th. Thank you!

**Comment by austinmama** [comment]
Hi @rich-ehrhardt.  Thanks again for your feedback.  I'm assuming that you mean the link that states:

[Create a certificate manager instance and import certificates]

We use "certificate manager" here to mean both Certificate Manager (uppercase) and Secrets Manager for now.   Until Certificate Manager is deprecated in Sept, it can still be used.   At that time, we will remove mention of Certificate Manager and change that reference to Secrets Manager.
