### ISSUE TITLE
Create a Custom Windows Image has incorrect cloud-init configuration

### ISSUE THREAD

**Issue by amarzulli** [ibm-cloud-docs/vpc#131]
Cloud-init conf files have the following definitions:

```
config_drive_types=vfat
config_drive_locations=hdd
```
They should be:
```
config_drive_types=vfat,iso
config_drive_locations=hdd,partition
```

**Comment by amatetic** [comment]
This update was made and is now published: https://cloud.ibm.com/docs/vpc?topic=vpc-create-windows-custom-image#customize-virtual-machine
