### ISSUE TITLE
Creation of vpc internal communication

### ISSUE THREAD

**Issue by ChetanReddy1999** [ibm-cloud-docs/vpc#132]
Hi,
    I have created two VSI's inside vpc. And made them communicate each other using ping commands. But when I checked flow logs for the same I found no communication of these two VSI's is being recorded. When two VSI's communicate each other why does packets cross vpc and route the data again to same vpc. Can we make the VSI's communicate internally not moving out of vpc?

**Comment by ChetanReddy1999** [comment]
@gudrun-wolfgram Hi, Can you help me resolving my issue.!!

Thanks!!

**Comment by gudrun-wolfgram** [comment]
@ChetanReddy1999 - Thanks for reaching out. If you have not already, you could review some of the Networking conceptual information and Security group information. I'm sorry that I'm not able to offer more help than that. If the information in IBM Cloud Docs doesn't resolve your question, please contact Support. 

**About networking**
https://cloud.ibm.com/docs/vpc?topic=vpc-about-networking-for-vpc

**About security groups**
https://cloud.ibm.com/docs/vpc?topic=vpc-using-security-groups
