### ISSUE TITLE
Creating a floating IP Address

### ISSUE THREAD

**Issue by apanicker30** [ibm-cloud-docs/vpc#134]
The document under this section talks about a floating IP address
https://cloud.ibm.com/docs/vpc?topic=vpc-about-networking-for-vpc#floating-ip-for-external-connectivity

There is no reference on how to create it. Can you provide a link to a page on how to create it.

**Comment by austinmama** [comment]
@jbmitch Please publish the new content and post URL here.  Thank you.

**Comment by jbmitch** [comment]
Content has been added:

https://cloud.ibm.com/docs/vpc?topic=vpc-fip-about
https://cloud.ibm.com/docs/vpc?topic=vpc-fip-working
