### ISSUE TITLE
The flow log collector page lists 3 record types (ingress, egress, & internal) when there are only 2 (ingress & egress)

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/vpc#135]
https://cloud.ibm.com/docs/vpc?topic=vpc-fl-analyze&interface=ui#flow-log-object-format

" ibm_vpc_flowlogs_v1/account={account}/region={region}/vpc-id={vpc-id}/subnet-id={subnet-id}/endpoint-type=vnics/instance-id={vsi-id}/vnic-id={vnic-id}/record-type={all|ingress|egress|internal}/year={xxxx}/month={yy}/day={zz}/hour={hh}/stream-id={stream-id}/{sequence-number}.gz "

"{all|ingress|egress|internal} shows the type of traffic the flow includes."

According to the flow log team, there are no internal record types because all traffic is typed via ingress or egress.  See the following thread in #ibmcloud-flowlogs - 

https://ibm-cloudplatform.slack.com/archives/C0117873D0S/p1661427924284129?thread_ts=1661316847.450779&cid=C0117873D0S

**Comment by austinmama** [comment]
Thank you @john-d-burke.  Removed the "internal" choice from the topic.  Build just started...
