### ISSUE TITLE
Certificates Manager is deprecated

### ISSUE THREAD

**Issue by SeanDKendle** [ibm-cloud-docs/vpc#136]
![image](https://user-images.githubusercontent.com/5393604/187734326-4fb9be0c-4bbb-4d36-aff8-fe092d674a04.png)
Deprecation announcement

IBM Cloud Certificate Manager is deprecated. You will be able to continue working as normal until 30 September 2022. At that time you will no longer be able to create new instances of the service and the tile will be removed from the catalog. On 31 December 2022, support for the service will be removed and any existing instances will be deleted.

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-migrate-from-certificate-manager

https://cloud.ibm.com/docs/vpc?topic=vpc-vpn-create-server&interface=ui#vpn-client-to-site-prerequisites

Step 4 should direct the user to the Secrets Manager and provide instructions for importing a certificate there:

![image](https://user-images.githubusercontent.com/5393604/187734261-fc3cde10-d437-486d-b5ef-c3ac74ac6bd7.png)

**Comment by austinmama** [comment]
Thank you for your feedback.  On Sept 30th, VPN documentation will be updated to reflect Secrets Manager only.
