### ISSUE TITLE
Suggest to add additional guidance for copying public key

### ISSUE THREAD

**Issue by bdubwalters** [ibm-cloud-docs/vpc#137]
Would be helpful to provide more specificity for users in the ssh key step of setting up a VSI:

1. Navigate to the ~/.ssh/ directory
2. To copy your SSH Public Key cleanly to clipboard WITHOUT a trailing newline use

`cat ~/.ssh/id_rsa.pub | tr -d '\n' | pbcopy`

or (without cat)

`tr -d '\n' < ~/.ssh/id_rsa.pub | pbcopy`

3. Paste the clipboard into the 'Public key' field in the 'Create new key' sidebar

Note the Azure docs provide really detailed steps for setting up VMs: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-ssh-keys-detailed#provide-ssh-public-key-when-deploying-a-vm

**Comment by amatetic** [comment]
The SSH key content was updated with more detailed instructions on Locating, creating, and importing SSH Keys using the UI. For CLI, API, and Terraform, the content includes listing and importing your keys.

https://cloud.ibm.com/docs/vpc?topic=vpc-ssh-keys

https://cloud.ibm.com/docs/vpc?topic=vpc-managing-ssh-keys
