### ISSUE TITLE
Why do the docs direct you to Security Groups in Classic Infrastructure?

### ISSUE THREAD

**Issue by jamesbeltonIBM** [ibm-cloud-docs/vpc#139]
I think there is a big error in here..... the doc page is directing users to the CLASSIC INFRASTRUCTURE security groups page to update their VPC DEFAULT SECURITY GROUP.

**Comment by Lauren-Fulcher** [comment]
Thanks for this useful feedback @jamesbeltonIBM! I'm implementing changes in the procedural now to correct my mistake

**Comment by jamesbeltonIBM** [comment]
No worries @Lauren-Fulcher - happy to help :)
