### ISSUE TITLE
Setting up your API and CLI environment

### ISSUE THREAD

**Issue by JCalabuig** [ibm-cloud-docs/vpc#14]
Instructions in Step 3: Store the API endpoint as a variable are not clear

> Run the following command to store the API endpoint in a variable so it can be reused later in your session. For api_endpoint, use the API endpoint given to you during on-boarding.

Instead, I suggest to replace the previous paragraph with the text below, that is also used in the VPC on Classic Documentation here: https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-creating-a-vpc-using-the-rest-apis#step-3-store-the-api-endpoint-and-version-parameter-as-a-variable

>The API endpoints are per region and follow the convention https://<region>.iaas.cloud.ibm.com. To see the list of all available endpoints, refer to Creating a VPC in a different region.

Store the API endpoint in a variable so you can use it in API requests without having to type the full URL. For example, to store the us-south endpoint in a variable, run this command:

api_endpoint="https://us-south.iaas.cloud.ibm.com"

**Comment by depst** [comment]
Updated topic on staging
