### ISSUE TITLE
Exact menu instruction is missing in the vpc-client-to-site-authentication  Secret Manager

### ISSUE THREAD

**Issue by wakakoj** [ibm-cloud-docs/vpc#140]
Setting up client-to-site authentication | IBM Cloud Docs — https://cloud.ibm.com/docs/vpc?topic=vpc-client-to-site-authentication&interface=ui&locale=en#creating-iam-service-to-service
(After creating easyrsa certificate, importing the certificate to Secret Manager)

`On the Your certificates page, follow these steps to import the certificate:`

This part, I didn't understand where to go in the SecretManager menu.

The support helpedme this information. This instruction should also be added in the document.

```
Are you importing a certificate or creating a certificate?

Either way, please refer to the link below;

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-certificates&interface=ui#import-certificates

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-certificates&interface=ui#order-certificates

```

**Comment by austinmama** [comment]
Updated per VPN Development.  Thank you for your feedback.
