### ISSUE TITLE
SSH Keys Description

### ISSUE THREAD

**Issue by MarudiIBM** [ibm-cloud-docs/vpc#142]
It should be explicitly stated with examples of the extra line breaks that should be removed causing the "Error Parsing".
Remove heading and closing: ---- BEGIN SSH2 PUBLIC KEY ----
Also remove any section with comments in the generated keys.

**Comment by amatetic** [comment]
The SSH keys content was revised and the Before you Begin section is updated with this information:
https://cloud.ibm.com/docs/vpc?topic=vpc-ssh-keys&interface=ui#ssh-key-prereqs
