### ISSUE TITLE
Create file share > Create replica section needs updating

### ISSUE THREAD

**Issue by alissach** [ibm-cloud-docs/vpc#143]
The create replica section on file share provisioning will no longer be created in the same page. It's now a read-only field with a new label `Asynchronous replica`. Please update the documentation for https://cloud.ibm.com/docs/vpc?topic=vpc-file-storage-create&interface=ui > Create file share replica to reflect the change. Thanks! 
![image](https://user-images.githubusercontent.com/16602130/204849933-89eacecd-78c4-43b8-a3be-2266effb7ced.png)

@donslovenkai

**Comment by cknabe** [comment]
Good catch @alissach

**Comment by donslovenkai** [comment]
Doc topics about creating file shares and creating replica file shares are update and published.
