### ISSUE TITLE
Windows password only obtainable via the FIRST included SSH Key

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/vpc#144]
https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_windows

Per case CS3130066 and other cases:

https://watson.service-now.com/nav_to.do?uri=%2Fsn_customerservice_case.do%3Fsys_id%3Df3dbb01947ef919019f03e14846d4366%26sysparm_view%3Dcase

Only the first SSH key provided when provisioning a Windows VSI in VPC is able to get the unencrypted password with the 'ibmcloud is instance-initialization-values' command.  The documentation does not reflect this fact.

**Comment by gudrun-wolfgram** [comment]
Thanks @john-d-burke for reporting this. I've updated the Before you begin section, step 1 to include, " If multiple SSH keys were added when the instance was created, you must use the first SSH key that was added."
