### ISSUE TITLE
Screenshot is outdated Route Propagation page

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/vpc#145]
Screenshot is outdated Route Propagation page:
https://cloud.ibm.com/docs/vpc?topic=vpc-vpn-client-to-site-route-propagation

The look and file has changed and the options are different. It needs to be updated.

**Comment by austinmama** [comment]
Updated. Closing.  https://test.cloud.ibm.com/docs/vpc?topic=vpc-vpn-client-to-site-route-propagation&interface=ui
