### ISSUE TITLE
Am I the only person who thinks that the "tabs" should go UNDER the the line "You can list your flow log collectors by using the UI, the CLI, or the API."?

### ISSUE THREAD

**Issue by guy-hindle-ibm** [ibm-cloud-docs/vpc#146]
Took me a while to see the "tabs" 👎 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/48133267/214312777-4c3c7361-4ce5-4da5-82ef-820bea376ddc.png">

I'd have expected to see tabs **under** the text:
> You can list your flow log collectors by using the UI, the CLI, or the API.

**Comment by vickmuir** [comment]
Thank you for the feedback. The context switcher is part of the IBM Cloud Docs framework and not specific to VPC documentation. I will take your feedback back to the designers.
