### ISSUE TITLE
VSI profile bx2-128x512 and bx2d-128x512

### ISSUE THREAD

**Issue by nsatoru** [ibm-cloud-docs/vpc#148]
The number of cores for the following profiles in docs is supposed to be 64, not 114.
- bx2-128x512
- bx2d-128x512

Please correct them.

**Comment by amatetic** [comment]
Thank you for your feedback. This is now corrected:

https://cloud.ibm.com/docs/vpc?topic=vpc-profiles&interface=ui#balanced
