### ISSUE TITLE
Add Terraform sample create-contract 

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/vpc#149]
Please add create-contract to the list of Terraform samples:
https://github.com/ibm-hyper-protect/linuxone-vsi-automation-samples/tree/master/terraform-hpvs/create-contract - create an encrypted and signed contract

**Comment by gudrun-wolfgram** [comment]
@PanLiyuan @priyanayar - could one of you take a look at this? Thanks!

**Comment by PanLiyuan** [comment]
Adding `create-contract` to the list
https://github.ibm.com/cloud-docs/vpc/pull/1933/commits/eb059f23c03a4f897e5e4b818f2783831e6b5f52

@gudrun-wolfgram could you help to merge the PR above, and also this PR to publish https://github.ibm.com/cloud-docs/vpc/pull/1934? thanks!

**Comment by PanLiyuan** [comment]
Hi @Timo-1 
`create-contract` is added to the list:
https://cloud.ibm.com/docs/vpc?topic=vpc-terraform-for-hyper-protect-virtual-servers-for-vpc

**Comment by Timo-1** [comment]
Thanks @PanLiyuan  - looks good.
