### ISSUE TITLE
Instructions for policy based ingress routing do not work

### ISSUE THREAD

**Issue by DeanJesson** [ibm-cloud-docs/vpc#151]
When you get to step 6 (create connection), it does not work - the UI validation complains the peer CIDR must not overlap with the VPC address prefix (which was configured in step 2).
To get around this I had to delete the address prefix (i.e. revert step 2), perform step 6, and then recreate the address prefix (repeat step 2).

**Comment by austinmama** [comment]
This feedback issue was updated and tested by Development on Feb 27th, 2023.  The latest topic is at: https://test.cloud.ibm.com/docs/vpc?topic=vpc-vpn-policy-based-ingress-routing-integration-example
