### ISSUE TITLE
Add a line or two explaining the security rules for connecting to a z/OS instance

### ISSUE THREAD

**Issue by Roavill2** [ibm-cloud-docs/vpc#152]
In order to connect to a z/OS instance using a 3270 emulator - you need to connect to port 992 as is documented in this section of the docs currently - https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_zos#getting-connected-zos

However we have no information in the doc to inform users that they need to add a rule to their security group inbound rules that allows communication with port 992.

If we could add a line or note at the start of this section around security group rules then I think that would make it much simpler for users to follow.

I had a call with a client this morning who were struggling to connect and this was the reason, just missing the security group rule.

Thanks in advance.

**Comment by Hestia-Zhang** [comment]
Hi @Roavill2 
There's a note in the last paragraph of Step 2. You can refer to the [Reserved configurations](https://www.ibm.com/docs/en/wazi-aas/1.0.0?topic=vpc-configurations-in-zos-stock-images) in z/OS stock images when adding additional ports into the security group. We will highlight this note and also add it to Security group topics for inbound rules settings. Thanks for the suggestion.
When creating and connecting to z/OS VSIs, you can check out the section in the [Wazi as a Service documentation](https://www.ibm.com/docs/en/wazi-aas/1.0.0?topic=creating-zos-vsis-in-cloud-vpc) to see a more streamlined process.
