### ISSUE TITLE
docs custom image packer topic page

### ISSUE THREAD

**Issue by powellquiring** [ibm-cloud-docs/vpc#153]
https://cloud.ibm.com/docs/vpc?topic=vpc-planning-custom-images&interface=ui#custom-image-creation

The page mentions packer:

![image](https://user-images.githubusercontent.com/6932057/222774554-54cb163d-66fe-4bb8-841c-7aa45e1a33d6.png)

Packer is like terraform in that IBM provides a supported plugin to the packer tool.

Expected: A topic page that answers a few basic questions about packer with links to the packer docs at hashicorp and IBM plugin information with a getting started and a simple full example in github that can be used.

**Comment by amatetic** [comment]
Thank you for your feedback. I have created an item to for us to track and complete this issue.
