### ISSUE TITLE
Please describe in the docs that VPE for UDP services is not accessible over DL/TGW.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#154]
Hello,
VPE for UDP services (e.g., NTP) is not accessible over Direct Link/Transit Gateway.
Could you please describe this below?

https://cloud.ibm.com/docs/vpc?topic=vpc-limitations-vpe

Thank you,

**Comment by austinmama** [comment]
Confirmed and updated 4/05.  Thank you for your feedback.
