### ISSUE TITLE
About idle timeout on ALB.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#155]
Hello,
We can now configure idle timeout value on ALB for VPC.
https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes#vpc-march1023

The following information does not seem to be updated. Could you please update it to the latest information?
https://cloud.ibm.com/docs/vpc?topic=vpc-advanced-traffic-management&interface=api#connection-timeouts

Thank you,

**Comment by jbmitch** [comment]
@ytama Pushed an update, give it a few to replicate
