### ISSUE TITLE
Timeout of ALB.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#156]
Hi, 
https://cloud.ibm.com/docs/vpc?topic=vpc-advanced-traffic-management&interface=api#connection-timeouts

>Currently, you cannot customize these values.

This description is not correct. We can now customize the client-side and server-side idle timeout. Please check this release note.
https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes#vpc-march1023

And in the "idle timeout" low, it says timeout is "2 hours", but the default value is 50 seconds, and we can configure it up to 2 hours.
I think "50 seconds(default) to 2 hours" is an appropriate description.

Thanks,

**Comment by jbmitch** [comment]
Pushed a fix, give it a look once it replicates
