### ISSUE TITLE
Fix the Attestation page

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/vpc#158]
Page: https://cloud.ibm.com/docs/vpc?topic=vpc-about-attestation
Edit this sentence:
_Old:_
Check the attestation record se-checksums.txt and the signature file se-signature.bin under the /var/hyperprotect directory after after you log in to your Hyper Protect Virtual Servers for VPC instance.
_New:_
Obtain the attestation record se-checksums.txt and the signature file se-signature.bin from your Hyper Protect Virtual Servers for VPC instance. To do so, you can implement your container to provide the attestation record and the signature file. The attestation record and the signature file are made available to your container in the /var/hyperprotect directory.

Add this sentence 
_New_
Verify the signature of the attestation record:
`openssl sha256 -verify contract-public-key.pub -signature signature.bin se-checksums.txt`
_above / before the following sentence:_
You can now use the hashes from the attestation record for validation.

**Comment by PanLiyuan** [comment]
@Timo-1 thanks for the input!

Could you review? https://github.ibm.com/cloud-docs/vpc/pull/2052/files

**Comment by PanLiyuan** [comment]
@Timo-1 Should it be `se-signature.bin` instead of `signature.bin` in the command?

**Comment by Timo-1** [comment]
@PanLiyuan yes, you are right: `se-signature.bin` is correct

**Comment by PanLiyuan** [comment]
@gudrun-wolfgram please help to merge the PRs:
https://github.ibm.com/cloud-docs/vpc/pull/2052 (to draft)
https://github.ibm.com/cloud-docs/vpc/pull/2053 (to publish)
thanks!

**Comment by PanLiyuan** [comment]
Published https://cloud.ibm.com/docs/vpc?topic=vpc-about-attestation
