### ISSUE TITLE
Include Confidential Computing Demo link

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/vpc#159]
Hi, I would like to add [Confidential Computing Demo](https://mediacenter.ibm.com/media/Confidential+Computing+for+a+financial+transaction+using+Hyper+Protect+Virtual+Server+for+VPC/1_vv3j2oo6) link to the [Confidential Computing with LinuxONE](https://cloud.ibm.com/docs/vpc?topic=vpc-about-se) page

**Comment by austinmama** [comment]
@PanLiyuan

**Comment by PanLiyuan** [comment]
PR: https://github.ibm.com/cloud-docs/vpc/pull/2156/commits/1c7e795e168700dba43790574da41fa6ae3a552e
Gudrun will merge it later today

**Comment by sandeep-at-ibm** [comment]
thanks @PanLiyuan for following up on this

**Comment by PanLiyuan** [comment]
@sandeep-at-ibm The video is added https://cloud.ibm.com/docs/vpc?topic=vpc-about-se
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/49715221/234163055-9cf7fd2f-716f-49e8-bad9-42f400cdf336.png">
You can close this issue if there's nothing else.

Thank you!

**Comment by sandeep-at-ibm** [comment]
thanks @PanLiyuan

**Comment by austinmama** [comment]
Closing.... Thank you!
