### ISSUE TITLE
Update VPC network diagram for completeness

### ISSUE THREAD

**Issue by ashutoshmate** [ibm-cloud-docs/vpc#16]
Since VPC can span multiple zones, in the diagram on this page: https://cloud.ibm.com/docs/vpc?topic=vpc-about-networking-for-vpc please show a "Zone2" with "subnet3" in the same "VPC1" to pictorially show that a VPC in a region can span multiple zones in the region.

**Comment by austinmama** [comment]
@sheltons Please update diagram using graphic process.  Thank you.

**Comment by austinmama** [comment]
@sheltons

**Comment by sheltons** [comment]
Sent request to graphics team. Will update when I hear back.

**Comment by sheltons** [comment]
Did not receive new image, but did receive notification that it's in the works. I mis-read the comment in the slack channel.

**Comment by sheltons** [comment]
![vpc-experience-simple](https://user-images.githubusercontent.com/20952798/112874630-c3cee400-9088-11eb-80c2-06594ba54140.png)

**Comment by austinmama** [comment]
@sheltons  Completed?

**Comment by sheltons** [comment]
Yes. Closing
