### ISSUE TITLE
wrong username

### ISSUE THREAD

**Issue by manish-soni1** [ibm-cloud-docs/vpc#160]
Hi, 
I was referring this document and came to know that the correct username should be ./administrator whereas in the doc, it is written as ./Administrator which didn't work in my case. So please check and correct the username, I struggled a lot because of this misinformation.

**Comment by gudrun-wolfgram** [comment]
Hi @manish-soni1 - thank you for reporting this issue. 

Can you verify if this was the topic that you are referring to, please?

**Connecting to a Windows bare metal server**
https://cloud.ibm.com/docs/vpc?topic=vpc-bare_metal_server_connecting_windows

**Comment by manish-soni1** [comment]
Hi @gudrun-wolfgram ,

Actually, I was referring to topic for windows virtual server for VPC : 
https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_windows

But somehow, I ended up posting for the bare metal server. However same should apply for bare metal also.

**Comment by gudrun-wolfgram** [comment]
@manish-soni1 - thank you for your response and additional information.

**Comment by jmilst** [comment]
The line now says: 

> If you're connecting from a client that is running the Windows Administrator account, use .\administrator as the user ID to log on to RDP.

Thanks again, @manish-soni1.
