### ISSUE TITLE
Doc issue: Broken link at page "Encryption and isolation"  

### ISSUE THREAD

**Issue by sofia-herrera** [ibm-cloud-docs/vpc#161]
1. What are the details of the issue you're experiencing?
     Broken link on below page:

**page**: https://cloud.ibm.com/docs/vpc?topic=vpc-instance-storage
**paragraph** : 1th  from 'Encryption and isolation'
**Broken link**: "Introduction to encryption."

2. Is this issue in reference to a specific page? If so, please provide a link.
Yes , the specific page "https://cloud.ibm.com/docs/vpc?topic=vpc-instance-storage" contains an hyperlink broken.
That link is located in first paragraph from "Encryption and isolation"
The broken hyperlink caption is : "Introduction to encryption."

![image](https://user-images.githubusercontent.com/130024931/233754980-d08423f7-d55a-41a9-9df9-463dd561279d.png)

3. Do you have a suggestion about how to resolve the issue?
IT should open the correct  page.

**Comment by gudrun-wolfgram** [comment]
Thanks for reporting this broken link. We'll take a look soon.

**Comment by amatetic** [comment]
The content that the link went to is removed and thus I have removed the link from this content. I have verified that the paragraph is complete as-is.
