### ISSUE TITLE
Documentation Missing for Fedore CoreOS ssh connection

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/vpc#162]
Per case CS3340558, customer was unable to use these instructions to ssh into their new Fedora VSIs.  They know their key pair is working because they used it successfully with a CentOS instance.

It turns out that the default administrative user in Fedora OS is not 'root', but instead 'core'.  When customer ran "ssh core@<FLOATING_IP>, they were then able to log in using their ssh key pair.  But this is not documented in this page, leading to customer confusion.  Here is supporting documentation confirming that the default administrative user for Fedora CoreOS is 'core'.  Please update this page to reflect this fact.  Thanks!

**Comment by austinmama** [comment]
Looks to be file_storage_vpc_mount_share_vsi.md file.  Thanks, John!

**Comment by vickmuir** [comment]
That topic has not been published in production, yet. I added a note for the Fedora exception, though.

In production, I found 3 topics (console-tutorial.md, creating-vpc-resources.md, and vsi_is_connecting_linux_gc.md) that showed the `ssh` command with `@root` so I added a note to them as well.
