### ISSUE TITLE
Broken link for:  [Creating a VPC by using the CLI]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc#163]
https://cloud.ibm.com/docs/vpc?topic=vpc-using-acls

![image](https://user-images.githubusercontent.com/131889203/234647115-fa7766e0-e8ac-4051-9ee4-e568587f942b.png)
![image](https://user-images.githubusercontent.com/131889203/234647131-dbb11447-9ef0-4df7-bdf9-3329d6de79b4.png)

broken link for:  [Creating a VPC by using the CLI](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-a-vpc-using-cli)

**Comment by austinmama** [comment]
Thank you for your feedback.  Fixed here and also in security groups section.
