### ISSUE TITLE
Broken link for: [Using the CLI to create VPC resources]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc#164]
https://cloud.ibm.com/docs/vpc?topic=vpc-about-vpc#about-vpc
broken link for: [Using the CLI to create VPC resources](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-a-vpc-using-cli)

![image](https://user-images.githubusercontent.com/131889203/234647962-94f1fd10-d147-4f9c-872b-8872d5ca8c75.png)
![image](https://user-images.githubusercontent.com/131889203/234647978-b2e1b685-80e1-4f3b-a1d6-0ac63015cbc0.png)

**Comment by austinmama** [comment]
Published today.  Thank you for your feedback.
