### ISSUE TITLE
Broken link for: [Using the REST APIs to create VPC resources]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc#165]
https://cloud.ibm.com/docs/vpc?topic=vpc-about-vpc#about-vpc
broken link for: [Using the REST APIs to create VPC resources](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-a-vpc-using-the-rest-apis)

![image](https://user-images.githubusercontent.com/131889203/234648361-7863f2dd-5704-4b99-bf24-896a0b510e19.png)
![image](https://user-images.githubusercontent.com/131889203/234648382-7f9850a6-aab8-40a7-b6bb-c52240f5bfa8.png)

**Comment by austinmama** [comment]
Thank you for your feedback. Published today.  Thanks again.
