### ISSUE TITLE
Broken link for: [Creating VPC resources]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc#166]
https://cloud.ibm.com/docs/vpc?topic=vpc-set-up-environment&interface=cli#cli-prerequisites-setup

broken link for: [Creating VPC resources](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-vpc-resources&interface=cli).
![image](https://user-images.githubusercontent.com/131889203/234649417-b5dbd508-cfc5-4677-a8f5-14b40ae013cf.png)
![image](https://user-images.githubusercontent.com/131889203/234649442-a0ee2ecb-8ec3-4e29-b848-80d4afc64d06.png)

**Comment by austinmama** [comment]
Thanks for your feedback. Fixed.  Closing.
