### ISSUE TITLE
Broken link for: [Getting started with custom images]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc#167]
https://cloud.ibm.com/docs/vpc?topic=vpc-importing-custom-images-vpc&interface=ui

broken link for: [Getting started with custom images](https://cloud.ibm.com/docs/vpc?topic=vpc-about-custom-images)

![image](https://user-images.githubusercontent.com/131889203/234654862-3b19a134-a4bc-42a3-b7e8-94cd4cc593d5.png)
![image](https://user-images.githubusercontent.com/131889203/234654879-f4a13fa4-f48c-41f2-aee0-873d7232fc28.png)

**Comment by vickmuir** [comment]
This has been resolved through commit: https://github.com/ibm-cloud-docs/vpc/commit/2d60040575b36002a93f8ef36fc32cb30d88924a
