### ISSUE TITLE
Broken link for: [Importing a custom image]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc#168]
https://cloud.ibm.com/docs/vpc?topic=vpc-byol-vpc-about

broken link for: [Importing a custom image](https://cloud.ibm.com/docs/vpc?topic=vpc-managing-images#import-custom-image)

![image](https://user-images.githubusercontent.com/131889203/234655176-c505f6c4-7af2-4726-b6ef-1c7a7ba48677.png)

![image](https://user-images.githubusercontent.com/131889203/234655204-f3133e07-9c99-420d-8e77-a125056be321.png)

**Comment by vickmuir** [comment]
This has been resolved through commit: https://github.com/ibm-cloud-docs/vpc/commit/2d60040575b36002a93f8ef36fc32cb30d88924a
