### ISSUE TITLE
Broken link for:  [Creating an instance by using the CLI]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc#169]
https://cloud.ibm.com/docs/vpc?topic=vpc-about-images

broken link for:  [Creating an instance by using the CLI](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-virtual-servers-cli)

![image](https://user-images.githubusercontent.com/131889203/234655765-d39ab71a-3ee6-4e5b-bff6-3221baf24a21.png)
![image](https://user-images.githubusercontent.com/131889203/234655787-c07f1b59-7000-460b-9053-e7ba0de6deab.png)

**Comment by austinmama** [comment]
Thank you for your feedback.  Fixed by @vickmuir.
