### ISSUE TITLE
Flow log pricing FAQ link goes to VSI provisioning page

### ISSUE THREAD

**Issue by jpapejr** [ibm-cloud-docs/vpc#170]
Docpage - https://cloud.ibm.com/docs/vpc?topic=vpc-flow-logs#fl-overview-of-features

<img width="772" alt="Screenshot 2023-05-04 at 9 00 35 AM" src="https://user-images.githubusercontent.com/213203/236212059-17f08609-d083-4e81-9e25-f542b20d745f.png">

Link in blue box says it's going to https://www.ibm.com/cloud/vpc/pricing#product-faq-section but actually goes to https://cloud.ibm.com/vpc-ext/provision/vs#product-faq-section

It's not apparent to me where the actual doc topic is in the site map so I've no way to know what the pricing model is for VPC Flow Logs.

**Comment by austinmama** [comment]
Thank you for your feedback.  On 4/1, pricing was removed from IBM Cloud Docs and product marketing pages.  Pricing is only available via the cost estimator now.  You can access it via the [flow logs provisioning page](https://cloud.ibm.com/vpc-ext/provision/flowLog).  I have removed the incorrect, redirected link above.  Thanks again!

https://www.ibm.com/cloud/cloud-calculator

**Comment by jpapejr** [comment]
Doesn't appear to work.. 
<img width="395" alt="Screenshot 2023-05-12 at 9 21 20 AM" src="https://github.com/ibm-cloud-docs/vpc/assets/213203/3e8d66ee-398d-4636-b8c3-2b1f5a73c54e">


Regardless of the selection, no estimate ever comes up, hence my attempt to locate pricing info in the docs.

**Comment by jpapejr** [comment]
@austinmama Any ideas on the above?
