### ISSUE TITLE
 Add cbr as VPE-enabled service into this doc: https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services

### ISSUE THREAD

**Issue by zhenwan** [ibm-cloud-docs/vpc#172]
Please add `Context-based Restriction`as VPE-enabled service into this doc: https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services

API Doc:
https://cloud.ibm.com/apidocs/context-based-restrictions?code=go#endpoint-urls
https://test.cloud.ibm.com/apidocs/context-based-restrictions?code=go#endpoint-urls

**Comment by austinmama** [comment]
@zhenwan Do you have instructions to point to similar to other services listed on the page above?

**Comment by zhenwan** [comment]
yes, the links I provided above are `Endpoint URLs`, the first one is for prod, and the second one is for staging. Can you please let me know when our service can be added into VPC doc web page.

**Comment by zhenwan** [comment]
@austinmama I just submitted a PR about this issue, please review https://github.com/ibm-cloud-docs/vpc/pull/174

**Comment by zhenwan** [comment]
PR got merged, closing this issue now
