### ISSUE TITLE
Ambiguity in certain VPN for VPC docs page

### ISSUE THREAD

**Issue by mlinnem** [ibm-cloud-docs/vpc#173]
On the page https://cloud.ibm.com/docs/vpc?topic=vpc-vpn-client-environment-setup

"Option 1" isn't clear. Opening the .ovpn file gives the following more clear directions:

"

/# Uncomment the next two lines if certificate-based client authentication is enabled.
/#  Ask your VPN administrator provides your client certificate and replace client_public_key
/#  with your client certificate filename.
/#cert client_public_key.crt
/#key client_private_key.key
"

Also if this can be escalated up to design/dev/PM, it's a pretty unusual process to have to combine two files by hand as suggested.

**Comment by austinmama** [comment]
@mlinnem Thank you for your feedback.  I will review/update the topic.  I will also escalate this issue to our designer/PM.

**Comment by mlinnem** [comment]
Thank you!

**Comment by mlinnem** [comment]
btw, just found the following page that bears a strong resemblance to the one in question: https://cloud.ibm.com/docs/vpc?topic=vpc-setting-up-vpn-client

Might be a piece of the puzzle if you weren't already aware. It seems to have some somewhat clearer language and some more details on it.

**Comment by austinmama** [comment]
The topic in question was recently updated.  Now, it not only includes a link to the Setting up a VPN client tutorial, but there is now an [automated client certificate authentication process for private certificates](https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes#vpc-nov1623).
