### ISSUE TITLE
minor changes to HPVS tutorial

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/vpc#175]
Please make changes as follows:

Title: Deploying a sample application on Hyper Protect Virtual Server for VPC

sub-title: This tutorial walks you through the steps to deploy a sample application on Hyper Protect Virtual Server for VPC that highlights how Confidential Computing can help protect PII. 

Introduction: Confidential Computing is the protection of data-in-use through a hardware-based technique. The sample application "PayNow" obtains and processes Personally Identifiable Information (PII) and credit card information for a financial transaction.

**Comment by gudrun-wolfgram** [comment]
@liuxjep - Could you take a look at this issue? Thank you!

**Comment by liuxjep** [comment]
@sandeep-at-ibm Hi Sandeep. Thanks for the comments. I made some small tweaks and created these two PRs for updates:
- For test: https://github.ibm.com/cloud-docs/vpc/pull/2357/files
- For publish: https://github.ibm.com/cloud-docs/vpc/pull/2358/files

@gudrun-wolfgram Gudrun will help merge the PRs. Thanks.

**Comment by sandeep-at-ibm** [comment]
thanks @gudrun-wolfgram & @liuxjep for following up
pls share link to the updated doc

**Comment by gudrun-wolfgram** [comment]
@sandeep-at-ibm 

**Deploying a sample application on Hyper Protect Virtual Server for VPC**
https://cloud.ibm.com/docs/vpc?topic=vpc-financial-transaction-confidential-computing-on-hyper-protect-virtual-server-for-vpc&interface=ui
