### ISSUE TITLE
Typo error for the command on step 2 of Connecting to your Windows bare metal server 

### ISSUE THREAD

**Issue by teoks** [ibm-cloud-docs/vpc#176]
https://cloud.ibm.com/docs/vpc?topic=vpc-bare_metal_server_connecting_windows#bare_metal_server_connect_windows

Connecting to your Windows bare metal server
2. Run the following command to initialize your server and obtain your password. Specify your server ID for the SERVER_ID variable and your private key for the KEY or KEY_FILE variable:

ibmcloud is  bare-metal-server-initialialization-values SERVER_ID [--private-key (KEY | @KEY_FILE)]

typo error for 
ibmcloud is bare-metal-server-initialialization-values
please change it to 
ibmcloud is bare-metal-server-initialization-values

**Comment by keith-merchant-ibm** [comment]
Closing and tracking internally.

**Comment by vickmuir** [comment]
This was resolved through https://github.com/ibm-cloud-docs/vpc/commit/7ada0003b8c888ffca5ebaa9f89561da11fac096
