### ISSUE TITLE
wrong spelling of SUSE operating system

### ISSUE THREAD

**Issue by luigimariano** [ibm-cloud-docs/vpc#178]
The list of supported OS for Bare Metal in VPC environment has a wrong spelling for SUSE "SUSE Red Hat Enterprise Linux for SAP" while it should be "SUSE Linux Enterprise Server (SLES) for SAP" as is used on this doc link:
https://cloud.ibm.com/docs/sap?topic=sap-compute-os-design-considerations

**Comment by gudrun-wolfgram** [comment]
@luigimariano - thank you for your feedback! 

I'm not able to find any occurrence of "SUSE Red Hat..." in the topic that you linked. I'm closing this issue.
