### ISSUE TITLE
Data Center Latencies Missing Classic sites

### ISSUE THREAD

**Issue by phoneline99** [ibm-cloud-docs/vpc#179]
Will this be updated to include the classic only sites?  I need to know latency between TOR, WDC and MON locations. Montreal being a classic only does not show up in your charts.  The previous lg.softlayer.com provided this info. Thank you.

**Comment by austinmama** [comment]
Hi Rene. The offering manager (Amudha) is aware of this.  I don't know if there are plans to add Classic, but will bring it up again to ensure your feedback is heard. Right now, for Classic, this site is still being used: http://lg.softlayer.com/
