### ISSUE TITLE
Error: Dedicated Host for Windows BYOL

### ISSUE THREAD

**Issue by izaskuns** [ibm-cloud-docs/vpc#180]
The VPC doc in this section: https://cloud.ibm.com/docs/vpc?topic=vpc-creating-virtual-servers&interface=ui&locale=en#creating-virtual-servers-ui
indicates in the Hosting type field in Table 1 that: "A dedicated host is required if you use a Windows custom image and [your own license](https://cloud.ibm.com/docs/vpc?topic=vpc-byol-vpc-about#byol-vpc-windows)."

This requirement is no longer true. Actually, if you click on the indicated link, it says: "Privileged users within your account can use the Windows BYOL custom image to provision an instance on a single-tenant dedicated host or on a shared, multi-tenant host."

**Comment by gudrun-wolfgram** [comment]
@izaskuns - thank you for reporting this issue. This content has been updated. The Add to dedicated host option is now included in the Advanced options section that is discussed in step 5 of this topic.
