### ISSUE TITLE
Numbering does not match instructions

### ISSUE THREAD

**Issue by rhocheck** [ibm-cloud-docs/vpc#183]
https://cloud.ibm.com/docs/vpc?topic=vpc-migrate-vsi-to-vpc

There are no steps 4.d to 4.h. Please be clear about what to do.

Install and configure Cloudbase-Init by completing steps 4.d through 4.h in [Creating a Windows custom image](https://cloud.ibm.com/docs/vpc?topic=vpc-create-windows-custom-image). Make sure to modify the Cloudbase-Init configuration files and Unattend file according to the instructions and then run Sysprep.

**Comment by gudrun-wolfgram** [comment]
Thanks - we'll look at getting this updated to remove the d and h.

**Comment by vickmuir** [comment]
Thank you for your feedback. The [topic](https://cloud.ibm.com/docs/vpc?topic=vpc-migrate-vsi-to-vpc#customize-windows-instance) has been updated.
![Screenshot 2023-10-24 at 1 42 37 PM](https://github.com/ibm-cloud-docs/vpc/assets/28069378/0e090636-6467-4ffc-824e-bfa7d1e9419d)
