### ISSUE TITLE
Security best practices for the instance metadata service does not mention configuring HTTPS

### ISSUE THREAD

**Issue by jjfall** [ibm-cloud-docs/vpc#184]
The metadata service was updated to support a secure (HTTPS) connection from the guest VM to the metadata service, but the [subject article](https://cloud.ibm.com/docs/vpc?topic=vpc-imd-security-best-practices&interface=ui) was not updated to advise a customer to configure their metadata service for a secure connection.

Here is the article that can be referenced in a new section in the best practices article:  https://cloud.ibm.com/docs/vpc?topic=vpc-imd-configure-service&interface=ui#secure-access-ui

Please reach out to the metadata team to ask for help on this update at #instance-metadata-dev or #instance-metadata-support.  @fode is the architect/lead.  Thank you.

**Comment by keith-merchant-ibm** [comment]
Closing and tracking internally.
