### ISSUE TITLE
Pointing to "one" downloads link

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/vpc#185]
I think it makes more sense to point to "one" downloads folder in the "Downloading the Certificates" section as the versions mentioned currently can change in the very near future, at which time this doc will become obsolete and will need to be updated on a regular basis.

Referring Doc link: https://cloud.ibm.com/docs/vpc?topic=vpc-cert_validate

**Comment by gudrun-wolfgram** [comment]
@priyanayar - could you take a look at this item? Thanks!

**Comment by priyanayar** [comment]
We cannot have a downloads folder because the IBM Cloud downloads site doesn't support it. 

You can upload multiple certificates to the folder in the downloads, but then you would need to provide multiple links. There isn't a way to link to a folder of documents if that's what you're looking for.

https://test.cloud.ibm.com/docs/writing?topic=writing-download-assets

![image](https://github.com/ibm-cloud-docs/vpc/assets/63598942/285de8ed-41b5-44f0-b68f-1cd0db373664)

**Comment by sandeep-at-ibm** [comment]
@priyanayar in that case, put them in a github-repo like what the HPCS team does for PKCS#11-library like this: https://github.com/IBM-Cloud/hpcs-pkcs11

Surely, we need to make sure our documents do not become obsolete and let the customer wonder if they are in fact downloading the latest version there is

**Comment by priyanayar** [comment]
Thanks @sandeep-at-ibm . I will talk to the developers and once they create the repo for it, I will link that repo in the docs. I will check if another issue is required for creating the repo, for the dev team to work on.

**Comment by sandeep-at-ibm** [comment]
@priyanayar thanks and please provide an ETA.
There is an ongoing issue being reported here: https://ibm-systems-z.slack.com/archives/CGYEHGVMX/p1692978289196809

**Comment by priyanayar** [comment]
@sandeep-at-ibm : After the development team creates the repo and populates it with the certificate and perhaps the CRL, I will update the docs to point to this.

I raised an issue for dev: https://github.ibm.com/ZaaS/hyper-protect-layer/issues/1182

**Comment by sandeep-at-ibm** [comment]
thanks @priyanayar

**Comment by priyanayar** [comment]
This issue can be closed and the dev issue will be followed up and doc updated when they have implemented this public repo.
