### ISSUE TITLE
The variable set in step 2 of load balancer create api is not used

### ISSUE THREAD

**Issue by mrshah-at-work** [ibm-cloud-docs/vpc#186]
The variable `ResourceGroupId` set in step 2 for use in step 3 is not used in step 3.

Link to doc: https://cloud.ibm.com/docs/vpc?topic=vpc-nlb-ui-creating-network-load-balancer&interface=api
Link to code: https://github.com/ibm-cloud-docs/vpc/blob/master/nlb-create.md?plain=1#L298-L370

Snapshot:
![image](https://github.com/ibm-cloud-docs/vpc/assets/15948008/03d992d5-44f2-465b-86e3-fdbb641d38b6)

**Comment by austinmama** [comment]
@jbmitch For your attention
