### ISSUE TITLE
broken link Troubleshooting client-to-site VPN servers

### ISSUE THREAD

**Issue by gridhawk** [ibm-cloud-docs/vpc#187]
broken link to https://cloud.ibm.com/docs/vpc?topic=vpc-why-do-i-get-an-authentication-error-user-authentication-failed-when-connecting-to-vpn-server

Related Links: "Troubleshooting client-to-site VPN servers" - on https://cloud.ibm.com/docs/vpc?topic=vpc-vpn-client-to-site-overview

leads to page not found

please scroll to the very end of that page

and click the last link "Troubleshooting client-to-site VPN servers"

**Comment by gridhawk** [comment]
https://cloud.ibm.com/docs/vpc?topic=vpc-troubleshoot-vpn-client-hangs works?

**Comment by austinmama** [comment]
Thank you for your feedback.  This was fixed a few weeks ago.  Thanks again!
