### ISSUE TITLE
false code example

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/vpc#188]
the code example on this page is wrong.
page: https://cloud.ibm.com/docs/vpc?topic=vpc-configuring-the-security-group&interface=cli

code example:
ibmcloud is instance-create test-instance $vpc us-south-2 b-4x16 $subnet 1000 --image $image --keys $key --security-groups $sg

parameter --security-groups not existent and needs to be replaces with sgs

**Comment by gudrun-wolfgram** [comment]
Thanks @ThomasUllrich666 for reporting this.
