### ISSUE TITLE
VPN: Site-to-Site route based configuration for AWS peer needs reviewing

### ISSUE THREAD

**Issue by amar-ibm** [ibm-cloud-docs/vpc#189]
On a recent client connection using a route-based site-to-site VPN to an AWS peer, we were advised by support and another IBM team that only 1 connection should be configured. 

However the documentation for a route-based configuration guides the client to set up 2 gateways on AWS side and configure 4 connections on the IBM Cloud VPN gateway side: https://cloud.ibm.com/docs/vpc?topic=vpc-aws-config&interface=ui#aws-config-static-route-based

Should the documentation for route-based site-to-site VPN to AWS peer be reviewed and updated to reflect the need for only 1 connection to avoid confusion?

**Comment by austinmama** [comment]
@amar-ibm Thank you for your feedback. Please see the latest, updated topic here: https://cloud.ibm.com/docs/vpc?topic=vpc-aws-config
