### ISSUE TITLE
Site-to-Site VPN limitations list should include notes on MTU limits

### ISSUE THREAD

**Issue by amar-ibm** [ibm-cloud-docs/vpc#190]
On a recent client connection, we had HTTPS connection issues over the VPN gateway connection from AWS using a route-based configuration.
Client has MTU set to 9000 on all their machine images (jumbo frames), which caused issues when trying to make HTTPS connections in particular and send / receive data.

We late came to discover PMTUD is not supported on site to site gateways, nor are jumbo frames or MTU settings over a certain limit in AWS: https://docs.aws.amazon.com/vpn/latest/s2svpn/vpn-limits.html

This information should also be added to the IBM Cloud VPN limitations documentation for more effective pre-setup planning and avoid downstream debugging issues: https://cloud.ibm.com/docs/vpc?topic=vpc-vpn-limitations

**Comment by austinmama** [comment]
@amar-ibm Added a new topic on MTU to the documentation and linked from the VPN limitation section.  If you have any comments on this new content, please contact me at dliburdi@us.ibm.com.  Thank you for your feedback.

https://test.cloud.ibm.com/docs/vpc?topic=vpc-about-mtu
