### ISSUE TITLE
Wrong information on what is available in /var/hyperprotect

### ISSUE THREAD

**Issue by VasiliyS** [ibm-cloud-docs/vpc#191]
The documentation states that `/var/hyperprotect` directory contains the following:

```
/var/hyperprotect
|-- cidata
|   |-- meta-data
|   |-- user-data
|   `-- vendor-data
|-- README
|-- se-checksums.txt[.enc]
|-- se-signature.bin
|-- se-commit-id
|-- se-version
`-- user-data.decrypted 
```

In reality ( HPCR v23.6.1)  it contains:

```
/var/hyperprotect
|-- cidata
|   |-- meta-data
|   `-- vendor-data
|-- se-checksums.txt[.enc]
|-- se-signature.bin
|-- se-version
`-- user-data.decrypted 
```

**Comment by gudrun-wolfgram** [comment]
This issue can be addressed by the Confidential Computing for LinuxONE team.

**Comment by vickmuir** [comment]
https://cloud.ibm.com/docs/vpc?topic=vpc-about-attestation#attestation_doc was updated in [commit ec95ec2](https://github.com/ibm-cloud-docs/vpc/commit/ec95ec24e1af59b5cbb2ac255f3b0e89159db9d6) to show:
```
/var/hyperprotect/
|-- cidata
|   |-- meta-data
|   |-- vendor-data
|-- se-checksums.txt
|-- se-signature.bin
|-- se-version
|-- user-data.decrypted
```
