### ISSUE TITLE
Attestation signature verification procedure doesn't work

### ISSUE THREAD

**Issue by VasiliyS** [ibm-cloud-docs/vpc#192]
the instructions on the [page](https://cloud.ibm.com/docs/vpc?topic=vpc-about-attestation) about  the Attestation
don't lead to a successful signature verification. 

```
openssl sha256 -verify contract-public-key.pub -signature se-signature.bin se-checksums.txt
Verification failure
80A065FC01000000:error:0200008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:crypto/rsa/rsa_pk1.c:75:
80A065FC01000000:error:02000072:rsa routines:rsa_ossl_public_decrypt:padding check failed:crypto/rsa/rsa_ossl.c:598:
80A065FC01000000:error:1C880004:Provider routines:rsa_verify:RSA lib:providers/implementations/signature/rsa_sig.c:788:
```

Which most likely means that the public key is incorrect. 

`openssl` version is `OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)`, running on MacOS M1.

[se-checksums.txt](https://github.com/ibm-cloud-docs/vpc/files/12690410/se-checksums.txt)
[se-signature.bin.zip](https://github.com/ibm-cloud-docs/vpc/files/12690472/se-signature.bin.zip)

**Comment by gudrun-wolfgram** [comment]
This issue can be addressed by the LinuxONE team.

**Comment by pranjank** [comment]
In this [page](https://cloud.ibm.com/docs/vpc?topic=vpc-about-attestation) you can see there is 2 certificates to support n-1 version. I hope you have selected right version of certificate to extract the public key.

**Comment by MargaretKanickaisamy** [comment]
The attestation certificates that are available in the [page](https://cloud.ibm.com/docs/vpc?topic=vpc-about-attestation) are already verified and correct at present. Hence, we can close this issue. If there is any other issue, feel free to raise another issue. 
Thanks!
