### ISSUE TITLE
Ammend VPC migration Document 

### ISSUE THREAD

**Issue by sltechs** [ibm-cloud-docs/vpc#193]
Regarding the instructions here:
https://cloud.ibm.com/docs/vpc?topic=vpc-create-windows-custom-image#customize-virtual-machine

There have been reports of issues with a successful migration with the instructions in that document. 

We found that running this script 
https://github.com/IBM-Cloud/vpc-server-migration/blob/main/server-migration-scripts/windows_precheck.ps1

Prior to sysprep was able to resolve the issues the client was facing. 
So it would be helpful to ammend the document such that the script where added in. 

Maybe a reference to it, something like:
If you run into issues successfully deploying the image in VPC. You can potentially attempt run the following script prior to  sysprep:
https://github.com/IBM-Cloud/vpc-server-migration/blob/main/server-migration-scripts/windows_precheck.ps1

**Comment by amatetic** [comment]
I am working on an issue to refresh the Migrating a virtual server from the classic infrastructure and Creating a custom windows image. When that content is published and available externally, I will update this github issue with the links.

**Comment by amatetic** [comment]
Working with the ACS Compute team, the Creating a custom Windows image completely reviewed and updated. You can review the changes here:
https://cloud.ibm.com/docs/vpc?topic=vpc-create-windows-custom-image

I will close this issue. If there are further issues, feel free to open a new github issue.
