### ISSUE TITLE
Creating a route in the CLI

### ISSUE THREAD

**Issue by heyfrancisco** [ibm-cloud-docs/vpc#196]
Hi team, 

I suggest adding a section with **Creating a route in the CLI** as we have already explaining how to do it in the UI portal.

https://cloud.ibm.com/docs/vpc?topic=vpc-create-vpc-route&interface=ui#cr-route-using-the-ui

Recently got a few questions from customers asking how to do it. Specially asking how they can create multiple routes from the CLI, since using the UI can take a long time doing one by one.

Many thanks.

**Comment by keith-merchant-ibm** [comment]
Tracking internally
