### ISSUE TITLE
bluemix command still there

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/vpc#197]
https://cloud.ibm.com/docs/vpc?topic=vpc-vpn-adding-connections&interface=cli

bx is vpn-gateway-connection-local-cidr-add VPN_GATEWAY CONNECTION PREFIX_ADDRESS PREFIX_LENGTH [--vpc VPC] [--output JSON] [-q, --quiet]

**Comment by sheltons** [comment]
Updated in stage and prod. Waiting for the build to finish to verify.

**Comment by sheltons** [comment]
bx removed. Closing.
