### ISSUE TITLE
Do not understand when/if my customer is affected

### ISSUE THREAD

**Issue by orebmann** [ibm-cloud-docs/vpc#202]
This article does not explain clearly which customers are affected and how they can prepare and prevent interruptions due to this change.

Hints like "Bookmark this guidance. When the feature becomes generally available, this page will be updated to include guidance on how to mitigate hazards introduced by the changes." are not really helpful for customers.

Can we please clearly state who is affected and what changes they need to make. Thanks a lot. 
Feel free to contact me so we can discuss (orebm@de.ibm.com)

**Comment by sheltons** [comment]
@orebmann See the Seismic information here: https://ibm.seismic.com/app?ContentId=510295c6-006e-43ab-b553-0b0d8d210980#/doccenter/f6bc8873-d580-4ee8-a903-c4e0d3a7eee9/doc/%252Fdd0ab3871f-9594-50fd-73b1-7f6c58815c13%252Fdd68496fc5-6bf7-f257-57bf-4d22ed665fcf%252Fddc9447fbd-62a9-f78c-7522-b548db99ded1%252Fdf1b8aaf07-a969-4d0b-9291-cf66b58662ad%252Fdf04c6e7db-5e13-475e-b6a7-0e076e6db96a%252Flf5c27bbde-c465-4733-bbff-6f736108bf72/grid/

For customers, you can refer them to the following links:
* https://cloud.ibm.com/docs/vpc?topic=vpc-vni-api-introduction#vni-api-affected — explains who is affected
* https://cloud.ibm.com/docs/vpc?topic=vpc-vni-api-introduction#vni-api-actions-preparing — explains about planning (can’t DO yet until GA release)
