### ISSUE TITLE
GPU name is not correct.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#203]
Hello,
In several places in this docs, it is mentioned as `L4Os`, but the correct name is `L40S`. (The third letter is the number zero.)
https://cloud.ibm.com/docs/vpc?topic=vpc-profiles&interface=ui

Please check this site.
https://www.nvidia.com/en-us/data-center/l40s/

**Comment by amatetic** [comment]
Thank you for catching that. I have updated both the profile documentation and the release notes:
https://cloud.ibm.com/docs/vpc?topic=vpc-profiles&interface=ui#gpu

https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes&interface=ui
