### ISSUE TITLE
In the release notes, it is mentioned as L4Os, but the correct name is L40S.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#204]
Hello,
In the release note, new GPU name is mentioned as `L4Os`, but the correct name is `L40S`. (The third letter is the number zero.)
https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes#vpc-feb2724

Please check this site.
https://www.nvidia.com/en-us/data-center/l40s/

**Comment by amatetic** [comment]
Thank you for catching that. I have updated both the profile documentation and the release notes:
https://cloud.ibm.com/docs/vpc?topic=vpc-profiles&interface=ui#gpu

https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes&interface=ui
