### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by gysel** [ibm-cloud-docs/vpc#208]
The release notes for 29 March 2024 "Sharing DNS resolution for endpoint gateways across VPCs" link to a non-existing page.

https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes&interface=ui#vpc-mar24

dead link: https://cloud.ibm.com/docs/vpc?topic=vpe-dns-sharing

the correct link might be https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-dns-sharing ?

**Comment by austinmama** [comment]
Thank you!  Fixed!   @amatetic 

 https://github.ibm.com/cloud-docs/vpc/pull/3332
