### ISSUE TITLE
instance-group-create examples are incorrect

### ISSUE THREAD

**Issue by sterlingbates** [ibm-cloud-docs/vpc#209]
https://cloud.ibm.com/docs/vpc?topic=vpc-bulk-provisioning&interface=cli#creating-instance-group-cli-bulk

`--subnet-ids` parameter should be `--subnets`

```
USAGE:
    ibmcloud is instance-group-create INSTANCE_GROUP_NAME --instance-template INSTANCE_TEMPLATE --subnets SUBNETS [--membership-count MEMBERSHIP_COUNT] [--lb LB --lb-pool LB_POOL --application-port APPLICATION_PORT] [--vpc VPC] [--resource-group-id RESOURCE_GROUP_ID | --resource-group-name RESOURCE_GROUP_NAME] [--output JSON] [-q, --quiet]
```

To that end, the CLI usage is actually wrong internally as it even suggests the wrong parameter in the examples:

```
ibmcloud is instance-group-create group-name --instance-template 72251a2e-d6c5-42b4-97b0-b5f8e8d1f479 --subnet 72b27b5c-f4b0-48bb-b954-5becc7c1dcb3,72b27b5c-f4b0-48bb-b954-5becc7c1dcb3
```

**Comment by vickmuir** [comment]
Thank you for your feedback, the command example will be updated shortly.

**Comment by vickmuir** [comment]
https://cloud.ibm.com/docs/vpc?topic=vpc-bulk-provisioning has been updated.
