### ISSUE TITLE
Link not rendered in 'Important' box: https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_best_practices

### ISSUE THREAD

**Issue by snorthov** [ibm-cloud-docs/vpc#21]
https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_best_practices

![image](https://user-images.githubusercontent.com/11139850/67803146-c75cd680-fa62-11e9-9c47-25e7a289674b.png)

See the image.  There's a weird "]" and the link is not rendered.

**Comment by depst** [comment]
Fixed link
