### ISSUE TITLE
Specifying Location when creating a instance template

### ISSUE THREAD

**Issue by vfandino** [ibm-cloud-docs/vpc#21]
What is the reason to specify a Location when creating an instance template? When you later create an instance group, you have to select there the subnets where the VSIs will be created

https://cloud.ibm.com/docs/vpc?topic=vpc-creating-auto-scale-instance-group#creating-instance-template

Reading the documentation, it is not clear that an instance template can be created and has sense without creating an instance group for load balancing after. Just a medium to define new instances

Thank you very much

**Comment by vfandino** [comment]
Also, the network interfaces information in the instance template seems to be unnecessary, because this depends on the selected subnets when you crean the instance group

Thank you

**Comment by gudrun-wolfgram** [comment]
@vfandino The topic you are referencing is a set of topics with a goal of creating an instance group. 

If you want to create an instance template for the sake of creating one or more instances, there is also this topic available...

Creating an instance template
https://cloud.ibm.com/docs/vpc?topic=vpc-create-instance-template

Thanks!

**Comment by vfandino** [comment]
@gudrun-wolfgram Thanks for your answer. You are right. I understand there is a single UI for, lets say, multi-purpose instance templates. However, I think we should document the meaning of selecting a Location when the goal is to create an instance template to support an instance group in an auto-scaling scenario. The same for the network interfaces.

Thank you very much
