### ISSUE TITLE
IAM instructions for setting permissions on 'console access' do not match the current GUI.

### ISSUE THREAD

**Issue by SammyC4IBM** [ibm-cloud-docs/vpc#212]
This page/section:

https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_console&interface=ui#vsi_is_connecting_console_prereq

The interface is much different now and likely to cause confusion.  (specifically, step C - - there is no 'additional access' section anymore).
Please walk thru the current UI to note the differences.

**Comment by vickmuir** [comment]
Thank you for your feedback, the topic will be updated shortly.
