### ISSUE TITLE
Load Balancer topic broken link

### ISSUE THREAD

**Issue by gbgrout** [ibm-cloud-docs/vpc#214]
The link on  https://cloud.ibm.com/docs/vpc?topic=vpc-nlb-vs-elb for Activity Tracker events -- https://cloud.ibm.com/docs/vpc?topic=vpc-at-events#events-load-balancers -- is broken.

**Comment by vickmuir** [comment]
Thank you for your feedback. The link has been restored by @Lauren-Fulcher two weeks ago.
