### ISSUE TITLE
EOS date for RHEL 8.10 minimal

### ISSUE THREAD

**Issue by tetsuofukuzaki** [ibm-cloud-docs/vpc#215]
The following End of support date for RHEL 8.10 minimal is missing from Table 4.
```
Operating system | End of support | License model
RHEL 8.10 minimal | 31 May 2029 | Pay-as-you-Go / BYOL
```
Table 4. Lifecycle for Red Hat Enterprise Linux (RHEL) operating systems
https://cloud.ibm.com/docs/vpc?topic=vpc-guest-os-lifecycle#rhel

**Comment by amatetic** [comment]
Thank you for your feedback. This update is completed:
https://cloud.ibm.com/docs/vpc?topic=vpc-guest-os-lifecycle#rhel
