### ISSUE TITLE
CLI docs - De-emphasize gen selection

### ISSUE THREAD

**Issue by deepaksibm** [ibm-cloud-docs/vpc#216]
IBM Cloud CLI infrastructure services automatically targets Gen 2 by default.

Hence the option gen2 should be de-emphasized

https://cloud.ibm.com/docs/vpc?topic=vpc-creating-vpc-resources-with-cli-and-api&interface=cli#select-the-generation

**Comment by vickmuir** [comment]
Docs issue was created CFD-7265, instructions will be updated shortly.

**Comment by vickmuir** [comment]
Update is complete. See commit [385f150](https://github.com/ibm-cloud-docs/vpc/commit/385f1503d462021583d5530709713d52a6ad4b3b)
