### ISSUE TITLE
Getting started with SSH keys

### ISSUE THREAD

**Issue by tooloudcajun** [ibm-cloud-docs/vpc#217]
Last updated date needs to be corrected, published page showing code "Last updated [{LAST_UPDATED_DATE}]"

**Comment by vickmuir** [comment]
Thank you for your feedback. The topic will be updated shortly.

**Comment by vickmuir** [comment]
The issue has been resolved through commit [78f6ac9](https://github.com/ibm-cloud-docs/vpc/commit/78f6ac9f28cb3c6a899fc7a81be2a0179e11ea13). See [Getting started with SSH keys](https://cloud.ibm.com/docs/vpc?topic=vpc-ssh-keys).
