### ISSUE TITLE
Date of last update is missing on documentation

### ISSUE THREAD

**Issue by lefurgy** [ibm-cloud-docs/vpc#219]
The page https://cloud.ibm.com/docs/vpc?topic=vpc-about-cloud-maintenance
literally has the words "[{LAST_UPDATED_DATE}]".

I believe it should be an actual date.

**Comment by vickmuir** [comment]
Thank you for your feedback. You're correct, the page should display the actual date it was last updated. 
https://cloud.ibm.com/docs/vpc?topic=vpc-about-cloud-maintenance is now showing the last updated date.
