### ISSUE TITLE
VPC Limitations Article is out of date

### ISSUE THREAD

**Issue by rminkov** [ibm-cloud-docs/vpc#22]
Hello,
This article:
https://cloud.ibm.com/docs/vpc?topic=vpc-limitations
needs to be updated - for example, it states that Windows and RHEL are not supported, but they actually are supported for Gen 1. They are not supported for Gen 2. The article does not mention Gen at all and that tells me it has not been updated recently. 
Thanks,
Ross

**Comment by stemke** [comment]
Thank you for reaching out and opening an issue. The limitations for generation 1 resources are documented here: https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-known-limitations.
