### ISSUE TITLE
Use Case 4 Description and Diagram Misleading

### ISSUE THREAD

**Issue by mekkim** [ibm-cloud-docs/vpc#222]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/vpc?topic=vpc-private-path-service-intro

### What do you think needs to be updated?

Use case 4's description looks copy-pasted from the previous use cases without the right adaptation for its distinctions.  For example, it says that the response is sent via DSR but the diagram doesn't show DSR arrow path.  Further, language of "provider" and "service" leaves out the "customer" so it's not clear what the customer's position is in the use case.  Are they the "provider" here?  Best to rephrase.

**Comment by Lauren-Fulcher** [comment]
Hi @mekkim, thank you for the feedback. We have made your suggested edits and updated the docs here: https://test.cloud.ibm.com/docs/vpc?topic=vpc-private-path-service-intro#pps-use-case-4
