### ISSUE TITLE
Icons missing on page About routing tables and routes

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/vpc#23]
Several icons are missing on this doc page. Plus it is mentioned `WORK-IN-PROGRESS`. That should be either updated or removed.

https://cloud.ibm.com/docs/vpc?topic=vpc-about-custom-routes

**Comment by austinmama** [comment]
Thank you @lionelmace  - A writer inadvertently uploaded information that was a work-in-progress.  Fixed!
