### ISSUE TITLE
Max IOPS in 3 IOPS/GB tier seems incorrect

### ISSUE THREAD

**Issue by weiminggu** [ibm-cloud-docs/vpc#25]
The Max IOPS for the 3 IOPS/GB tier is current set to "3 IOPS/GB up to 20,000 IOPS".  This doesn't seem to be correct.  With volume size max at 2 TB, the maximum IOPS should be "up to 6,000 IOPS".
I'm internal IBM engineer, btw.  wgu@us.ibm.com

**Comment by stemke** [comment]
Thank you, @weiminggu.  I've opened this issue on our internal jira board for investigation and will reach out to personally.  We appreciate the feedback.
