### ISSUE TITLE
Conflicting information on IP Spoofing

### ISSUE THREAD

**Issue by chanster** [ibm-cloud-docs/vpc#25]
[This](https://cloud.ibm.com/docs/vpc?topic=vpc-ip-spoofing-about) on IP spoofing says this is available for VPC.

I have contacted support as we have enabled the `IpSpoofingOperator` policy to our access group and we get `403` access  denied errors. Support states this is not supported in VPC.

The [IBM Terraform resource](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance#allow_ip_spoofing) states this option as available also.

I do not understand who is correct as the document and support are providing conflicting information.

**Comment by sheltons** [comment]
I've checked in with the developers, and this is the response:

It is possible that IAM is configured incorrectly. If the IAM role is not assigned to the correct userID in that account, it might not work. You'll also need the instance permissions to create an instance with a nic. 

We do have support for this. The documentation is correct.
