### ISSUE TITLE
Need section on configuring network performance including setting MTU 

### ISSUE THREAD

**Issue by AliseATX** [ibm-cloud-docs/vpc#26]
Need to validated and then add the following section to Gen2.  

https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-configuring-network-performance

Thanks,
Alise

**Comment by austinmama** [comment]
@sheltons

**Comment by sheltons** [comment]
It looks like this update was completed in https://github.ibm.com/cloud-docs/vpc/pull/557
Closing.
