### ISSUE TITLE
Steps for authorization of flow log is not valid anymore

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/vpc#27]
The steps in "Authorize resources of type Flow Logs for VPC to use the COS instance created in Step 2." are not valid anymore. The IAM authorization process is chanted

**Comment by austinmama** [comment]
Updated steps on 3/10.  Thank you for sending feedback!  https://cloud.ibm.com/docs/vpc?topic=vpc-ordering-flow-log-collector#fl-before-you-begin
