### ISSUE TITLE
Update for Power images on the specific locations where the Power images are provided

### ISSUE THREAD

**Issue by tommyk-enablement** [ibm-cloud-docs/vpc#27]
In the doc: 
https://cloud.ibm.com/docs/vpc?topic=vpc-about-images

Since we have begun to indicate the specific regions for the images for WDC, we should also indicate that the Power images are only in the DAL region. 
CentOS, Debian, Ubuntu with GPU support is for Power is DAL only.

**Comment by stemke** [comment]
Moving this to our CFD project.
