### ISSUE TITLE
Link to Hyper Protect Crypto Services VPE details doesn't work

### ISSUE THREAD

**Issue by steve-lievens** [ibm-cloud-docs/vpc#28]
On this page :
https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services

There's a link to get more info on IBM Cloud Hyper Protect Crypto Services VPE setup. That link points to :
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-virtual-private-endpoints-for-vpc

But this last link doesn't exist

**Comment by austinmama** [comment]
Thank you, @steve-lievens.  The writer has been informed that the page was not published correctly.  Forthcoming...

**Comment by austinmama** [comment]
@steve-lievens  Here is a copy of the page being published.  
[vpe-hpcs.pdf](https://github.com/ibm-cloud-docs/vpc/files/6076581/vpe-hpcs.pdf)

**Comment by steve-lievens** [comment]
Thanks a lot for your fast reply !!!

**Comment by austinmama** [comment]
Fixed!  Thanks again!
