### ISSUE TITLE
Creating a dedicated host in VPC - small typo

### ISSUE THREAD

**Issue by dlentz-ibm** [ibm-cloud-docs/vpc#29]
Hello all,
If you browse to this document:
https://cloud.ibm.com/docs/vpc?topic=vpc-creating-dedicated-hosts-instances

Scroll down to the 'Creating a Dedicated Host' section that contains three steps. In the first step you say:

_"In the IBM cloud console, go to Menu icon Menu icon > VPC Infrastructure > Compute > Dedicated hosts."_

The problem is that there is no such menu option. I think what you meant to say is:

_"In the IBM cloud console, go to Menu icon Menu icon > VPC Infrastructure. On the VPC landing page under compute, click on Dedicated Hosts"_

**Comment by gudrun-wolfgram** [comment]
Cascade menu is now available.
