### ISSUE TITLE
[Feature Request] Advanced routing: Subnet route table

### ISSUE THREAD

**Issue by IAmFrench** [ibm-cloud-docs/vpc#29]
Others cloud providers allow the creation of routing table at the subnet level

- [AWS Subnet Route Table](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html#route-table-assocation)
- [GCP Subnet routes](https://cloud.google.com/vpc/docs/routes#subnet-routes)

**Comment by stemke** [comment]
@IAmFrench - Thank you for your feedback. I've passed along your request to the Offering Management team for consideration. We appreciate the input.
