### ISSUE TITLE
Update list of what is available to VPC via mirrors.adn.networklayer.com

### ISSUE THREAD

**Issue by jayhawk87** [ibm-cloud-docs/vpc#30]
https://cloud.ibm.com/docs/vpc?topic=vpc-service-endpoints-for-vpc shows that Ubuntu and Debian images are all that is available from mirrors.adn.networklayer.com

We know that Fedora packages are also available, but what else may be?

**Comment by stemke** [comment]
Hi @jayhawk87 - Thanks for submitting this feedback. Moving this to our internal dev board and will reach out to give you a link.  Thanks.
