### ISSUE TITLE
Icons missing in architecture diagram on the ALB page 

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/vpc#30]
Some icons are missing in the architecture diagram on this page: 
https://cloud.ibm.com/docs/vpc?topic=vpc-load-balancers

![image](https://user-images.githubusercontent.com/12241613/110456697-2a846180-80ca-11eb-99de-34d6c8675cec.png)

**Comment by austinmama** [comment]
@jbmitch

**Comment by lionelmace** [comment]
@jbmitch Any fix plan shortly?

**Comment by austinmama** [comment]
@lionelmace  Jack working on it today.

**Comment by lionelmace** [comment]
Activity Tracker and Sysdig icons and names have changed recently. That might be worth updating them at the same time.

**Comment by austinmama** [comment]
@jbmitch  Completed?

**Comment by jbmitch** [comment]
Fixed
