### ISSUE TITLE
quota page is missing remote rules per security group

### ISSUE THREAD

**Issue by steve-gutierrez** [ibm-cloud-docs/vpc#31]
https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#security-group-quotas

should have a entry for remote rules:

Remote rules | 5 per security group

similar to the gen1 quota (https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-quotas#security-groups-quotas)

**Comment by austinmama** [comment]
Fixed.

**Comment by austinmama** [comment]
@steve-gutierrez   Offering Mgmt wants to keep the remote rules for Security Groups under Service Limits, not Quotas.  Here is the link:  https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#service-limits

Thank you for your feedback.
