### ISSUE TITLE
IBM VPC Monitoring services - link to content missing

### ISSUE THREAD

**Issue by fmerch** [ibm-cloud-docs/vpc#32]
I'm starting to set up a VPC and a VSI following the docs here:
https://cloud.ibm.com/docs/vpc?topic=vpc-creating-a-vpc-using-cli

Toward the bottom section on "Monitoring your instance", the link to get more information on "Monitoring services" is broken:

Monitoring your instance
You can monitor the CPU, volume, memory, and network usage of your instance over time in the IBM Cloud console. Because the monitoring data is stored in IBM Cloud Monitoring, you must be authenticated to an instance of the Monitoring service in your account. For more information, see **Monitoring services**.

Screenshot of what I'm seeing below:
https://cloud.ibm.com/docs/vpc?topic=cloud-infrastructure-sysdig-monitoring-metrics

![image](https://user-images.githubusercontent.com/55157874/112343883-c98b8a80-8c80-11eb-9693-0d1665813876.png)

**Comment by jmilst** [comment]
The link has been updated - thanks!

**Comment by gudrun-wolfgram** [comment]
Thanks for the feedback. The link is now updated.
