### ISSUE TITLE
ibmcloud is zones <region> is not a valid command

### ISSUE THREAD

**Issue by andrewferrier** [ibm-cloud-docs/vpc#33]
This page (https://cloud.ibm.com/docs/vpc?topic=vpc-creating-virtual-servers-cli), step 2, indicates to use `ibmcloud is zones <regionname>`. However, this is not a valid use of this command; it doesn't support an argument. It would be helpful if the command did work that way though! Instead, you have to log in to a region, then list the zones.

**Comment by vickmuir** [comment]
Thank you for your feedback. Although the link that you referenced no longer exists, I searched for the incorrect CLI command example and corrected it in other topics.
