### ISSUE TITLE
data triplication

### ISSUE THREAD

**Issue by dwarakanathprao** [ibm-cloud-docs/vpc#34]
Please review data triplication and accept my proposed changes data replication in GitHub.

**Comment by austinmama** [comment]
@DLM-IBM I don't see any PRs for these changes.  Believe it affects https://cloud.ibm.com/docs/vpc?topic=vpc-instance-storage

**Comment by vickmuir** [comment]
I could not find any PR in this repo or in the IBM Enterprise GitHub. Closing this issue.
