### ISSUE TITLE
Incorrect FAQ

### ISSUE THREAD

**Issue by movinglightspeed** [ibm-cloud-docs/vpc#35]
Hi VPC Team,

https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-vpc-faq#faq-block-storage-12
States Block storage for VPC has cloning, replication and shapshots but the current block storage for VPC does not have these feature, only ability to attach them to a server.

Please update incorrect FAQ.

Stanley S.
IBM Cloud Architect

**Comment by stemke** [comment]
Hi @movinglightspeed - Thank you for reaching out! We'll take a look asap and get this information updated.  We appreciate the feedback.

**Comment by stemke** [comment]
Issue resolved. Closing out.
