### ISSUE TITLE
Connecting to Windows instances

### ISSUE THREAD

**Issue by rgentyala** [ibm-cloud-docs/vpc#36]
Hello Team,

I am really struggling to manage connectivity to IBM Cloud Virtual Server Instance. What is an issue in documenting in clear steps that can enable. I have floating IP on IBM Cloud for my VSI but frankly speaking private key is a problem. This documentation is clearly helping connectivity part so clear in steps 1,2,3 whether they are part of IBM network or outside of IBM. Within IBM as we connect to IBM VPN things may be different otherwise if everything is similar through floating IP then these steps should be sequential and does not point to various other links that makes it difficult to work. Simple example and step by step information must be there so that our customers can feel comfortable.

https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_windows#vsi_connecting_windows_instance

**Comment by mterry** [comment]
@gudrun-wolfgram I'd like to hop on and clarify something w.r.t. connection issues + a solution for connecting to Windows instances in a new or fresh VPC environment.

A large part of the problem with the present documentation is that it assumes RDP port traffic (traffic over TCP/UDP 3389) are already allowed in the Security Group associated with the server port. If this step is documented in the VPC setup, I think a simple note at the bottom of the documentation that points to the VPC setup step would suffice; else wise, if this is not documented anywhere else in the manuals, I think it especially needs to be defined in the Connecting to Windows Instances section as a needed step.

**Comment by vickmuir** [comment]
Thank you for the feedback. It looks like the recommendation in the second comment was incorporated into the topic already and we forgot to update this issue. 
![Screenshot 2023-10-24 at 2 37 58 PM](https://github.com/ibm-cloud-docs/vpc/assets/28069378/77588988-3717-4878-bc7f-2e80423bb679)
