### ISSUE TITLE
Fix typos.. 

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/vpc#38]
https://cloud.ibm.com/docs/vpc?topic=vpc-user-data
![image](https://user-images.githubusercontent.com/11874942/115048626-c19dbf80-9ea7-11eb-9891-189d495e6539.png)

**Comment by gudrun-wolfgram** [comment]
Thanks @dprosper . These typos are resolved: https://cloud.ibm.com/docs/vpc?topic=vpc-user-data
