### ISSUE TITLE
Using Windows Client to connect to Windows Server

### ISSUE THREAD

**Issue by Aseronly1** [ibm-cloud-docs/vpc#38]
The documentation is very bad, I am using Windows Client to connect to Windows servers I don't Have CAT command and I can't find an easy step by step procedures to follow ...?!

Please we need a more easy way to connect to VPC windows servers ..

**Comment by gudrun-wolfgram** [comment]
Hi Aser, 
I'm sorry that you had problems with the Connecting to a Windows instance instructions. You might want to try using the **ibmcloud is instance-initialization-values** command to decode and decrypt the password https://cloud.ibm.com/docs/vpc?topic=vpc-infrastructure-cli-plugin-vpc-reference#instance-initialization-values

You can use the installed CLI, or you could try the IBM Cloud Shell Beta. 

**Tip:** Want to instantly start working with the IBM Cloud CLI? Try out IBM Cloud Shell (Beta), which gives you a personal cloud-based shell workspace with the full IBM Cloud CLI and tons of command-line tools - no installation needed. To get started, click the Cloud Shell icon IBM Cloud Shell icon in the IBM Cloud console menu bar. For more information, see Getting started with IBM Cloud Shell. https://test.cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-getting-started

I hope that helps!

**Comment by stemke** [comment]
Hi Aser, Your concerns have been communicated to the team. Hope that the recommendations above helped. If you continue to have problems, please contact support or if you have suggestions on specific additions/modifications to include in the documentation, feel free to contribute as well. We greatly appreciate you taking the time to reach out.
