### ISSUE TITLE
ibmcloud sdk command can be used to get the cos instance GUID

### ISSUE THREAD

**Issue by gnavgire** [ibm-cloud-docs/vpc#39]
Instead of going back and forth between the UI and the CLI, we can use the IBMCLOUD SDK command 
"ibmcloud resource service-instance "Cloud Object Storage-ch" to get the GUID of the COS service instance

**Comment by vickmuir** [comment]
This seems to be related to https://cloud.ibm.com/docs/vpc?topic=vpc-object-storage-prereq&interface=cli

![Screenshot 2023-10-24 at 2 53 31 PM](https://github.com/ibm-cloud-docs/vpc/assets/28069378/b93270ae-b7f9-4e4b-a130-c4ba1e3e6fa1)

**Comment by vickmuir** [comment]
Replaced the UI steps with the CLI command and example.
![Screenshot 2023-10-24 at 3 40 44 PM](https://github.com/ibm-cloud-docs/vpc/assets/28069378/8f705c3c-d1bb-407b-811e-62d556605042)
