### ISSUE TITLE
Getting 'is' is not a registered command. See 'ibmcloud help'.

### ISSUE THREAD

**Issue by obender** [ibm-cloud-docs/vpc#4]
Hi, I am trying to init windows instance an getting 'is' is not a registered command. See 'ibmcloud help'.

**Comment by stemke** [comment]
Hi @obender - Did you set up your CLI environment? If not, see https://cloud.ibm.com/docs/vpc?topic=vpc-set-up-environment#cli-prerequisites-setup.  If you continue to have trouble, please contact support for assistance.  Thanks for reaching out.
