### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AliseATX** [ibm-cloud-docs/vpc#40]
Contact IBM Support link is broken on the Quota request page. 

https://cloud.ibm.com/docs/vpc?topic=vpc-quotas

Should link to Create a Case in the IBM Console: https://cloud.ibm.com/unifiedsupport/cases/form

**Comment by gudrun-wolfgram** [comment]
Thanks @AliseATX. I've updated this link. The change should appear when the build is complete.
