### ISSUE TITLE
Need to add documentation about how to add vNICs 

### ISSUE THREAD

**Issue by bknapp-ibm** [ibm-cloud-docs/vpc#41]
Hey all.

So, we have no documentation about how to add/configure vNICs anywhere that I can find. 

I don't know that this is the right place for it, but I learned today that you have to order the new vNIC, stop the VSI, and then start it in order for cloud-init to invoke and add the interface to the VSI. 

Can we please get a new section somewhere that describes this?

**Comment by stemke** [comment]
Moved this into our project space for tracking. Thanks.
