### ISSUE TITLE
need to document max number of security groups allowed by network interface

### ISSUE THREAD

**Issue by steve-gutierrez** [ibm-cloud-docs/vpc#41]
hi, 
can we please add the following service limit,

Resource               Limit
Security Group     5 per network interface

here,
https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#service-limits

?
because a network interface (and the virtual machine it's attached to) will fail if a user tries to associated > 5 security groups with it,
https://jiracloud.swg.usma.ibm.com:8443/browse/RNOS-2380

this is a hardcoded limit and can't be adjusted like a quota can.
thank you

**Comment by austinmama** [comment]
This was added previously.  Thank you for your feedback.  Closing.

**Comment by steve-gutierrez** [comment]
thanks, but i don't see this in the table of service limits, are you sure it was added ? 
https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#service-limits

i see "Remote rules for security groups" but this issue was opened to add "Security Groups per network interface" . can you please double check?

thank you.

**Comment by austinmama** [comment]
Hi @steve-gutierrez  - The OM updated this recently under quotas, not service limits.  Let me know if this needs to be altered. Feel free to ping me on slack @dliburdi.

https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#security-group-quotas

![image](https://user-images.githubusercontent.com/29232369/128619953-63fd8591-3db1-4c5d-b908-abe05c0016e9.png)

**Comment by steve-gutierrez** [comment]
hi @austinmama - thanks. but the "5 security groups per NIC" isn't a quota (which implies it can be increased), it's a service limit (a hardcoded value in the code that can't be changed). i'll ping you on slack to follow up, have a great day.
