### ISSUE TITLE
Referenced docs have changed

### ISSUE THREAD

**Issue by joergrenn** [ibm-cloud-docs/vpc#42]
In section https://cloud.ibm.com/docs/vpc?topic=vpc-migrate-vsi-to-vpc#customize-windows-instance
Step 3 ist not working any more:
> Install and configure Cloudbase-Init by completing steps 4.d through 4.h in Creating a Windows custom image.

In the referenced docs "https://cloud.ibm.com/docs/vpc?topic=vpc-create-windows-custom-image"
there are no steps 4.d trough 4.h anymore. 
Can you please adapt the description?

**Comment by vickmuir** [comment]
Thank you for your feedback. Step 3 is updated.
