### ISSUE TITLE
Better guidance on enabling NAT-T

### ISSUE THREAD

**Issue by acursons** [ibm-cloud-docs/vpc#43]
On the page:
https://cloud.ibm.com/docs/vpc?topic=vpc-check-point-config
instructions are given as to how to put a checkpoint gateway into NAT-T mode. However these instructions assume the user is a Checkpoint expert. No mention is given of a cross reference or the command line or the GuiDBedit application for configuring gateway environment variables. 

The link below mentions to use GuiDBedit to set the variables
https://sc1.checkpoint.com/documents/R80.20_GA/WebAdminGuides/EN/CP_R80.20_SitetoSiteVPN_AdminGuide/html_frameset.htm?topic=documents/R80.20_GA/WebAdminGuides/EN/CP_R80.20_SitetoSiteVPN_AdminGuide/137002

**Comment by austinmama** [comment]
Waiting on response from Development

**Comment by austinmama** [comment]
Updated: https://cloud.ibm.com/docs/vpc?topic=vpc-check-point-config#checkpoint-defaults

Thank you for your feedback.
