### ISSUE TITLE
inaccessible Link: Example solution: Analyzing flow Logs for VPC using LogDNA

### ISSUE THREAD

**Issue by rayh0001** [ibm-cloud-docs/vpc#45]
Hi All,
It seems the link to Example solution: Analyzing flow Logs for VPC using LogDNA is not accessible to the IBM Cloud user. Can you give an alternate how this can be used with logDNA.   Thanks in advance. 
<img width="858" alt="Screen Shot 2020-07-27 at 4 24 52 PM" src="https://user-images.githubusercontent.com/6523736/88594092-397c3f00-d026-11ea-9f03-9d96c2bb69d5.png">

**Comment by austinmama** [comment]
Hi Ray and thank you for letting us know. The URL was updated to:

https://github.com/IBM-Cloud/vpc-flowlogs-logdna

I have updated the documentation.  Really appreciate your feedback!
