### ISSUE TITLE
Format issue on VPC Block Storage page

### ISSUE THREAD

**Issue by buckwem** [ibm-cloud-docs/vpc#46]
The format is wrong in this section
https://cloud.ibm.com/docs/vpc?topic=vpc-creating-block-storage#create-standalone-vol

**Comment by austinmama** [comment]
Informed Don Slovenkai

**Comment by vickmuir** [comment]
The issue has been resolved. https://cloud.ibm.com/docs/vpc?topic=vpc-creating-block-storage#create-standalone-vol looks normal.
