### ISSUE TITLE
To launch monitoring, the link name changed from Open dashboard to View IBM Cloud Monitoring

### ISSUE THREAD

**Issue by VidyasagarMSC** [ibm-cloud-docs/vpc#47]
As mentioned in the link here - https://cloud.ibm.com/docs/vpc?topic=vpc-monitoring-metrics-alb#working-with-monitoring-dashboard-alb, It's not **Open Dashboard** anymore. The link description has changed to **View IBM CLoud Monitoring**

**Comment by jbmitch** [comment]
Fixed
