### ISSUE TITLE
ACL rules for VPN need correction (table 1)

### ISSUE THREAD

**Issue by joergrenn** [ibm-cloud-docs/vpc#50]
The rules listed in table 1 are not correct in case that the VPN gateway and the ressources that communicate oven the tunnel are not in the same subnet. Putting VPN Gateway and VMs not in the same subnet is the recommended subnet.

Please refer to case CS2346016 for the details what is not corect:

> "the traffic in this case is routed from VSI subnet -> vpn subnet -> on prem. 
>so for VPN subnet ACL: 
>allow ipv4 all 10.243.64.0/25 0.0.0.0/0 SOURCE = VPC SUBNET INSTEAD OF ONPREM SUBNET; DEST ANY >INSTEAD OF VPC SUBNET 
>this is needed so VPN in it's separate subnet can receive traffic from the VSI subnet, then forward to on prem. 
>allow ipv4 all 0.0.0.0/0 10.243.64.0/25 SOURCE ANY INSTEAD OF VPC SUBNET; DEST VPC SUBNET INSTEAD >OF ONPREM SUBNET is needed so when we hear back from on-prem, we can forward it from vpn subnet to the >vsi subnet. The >original rules in the table, that did not work for customers, were meant for resources on same >subnet as the VPN."

>They have acknowledged that this should be clarified in the documentation, since we no longer recommend putting VPC resources on the same subnet as the VPN gateway itself, because when customers apply custom routes and firewalls intended to restrict traffic to those VSIs, they wind up restricting traffic to the VPN gateway's backend appliances as well.

Please update the documentation what is needed for VPN tunnel traffic to be routed from VPN gateway to and from VPC subnet.

**Comment by austinmama** [comment]
waiting on response from Development

**Comment by mark19830206** [comment]
Hi @austinmama maybe I missed something, as you can see, these rules are specified the vpn subnet and vpc vsi subnet are different
![image](https://user-images.githubusercontent.com/87261980/126741721-476af383-1d78-4633-a476-359e9ca64b7a.png)

and for VPN gateway subnet NACL, we specified two rules, with inbound and outbound. can you see who handled the ticket and ask him to clarify the issue

**Comment by joergrenn** [comment]
@mark19830206, yes you missed something. The rules are different, but they are still wrong in case a VSI and VPN gateway are not in the same VPC subnet.
Also it could be better distinguished between the subnet that hosts the VPN Gateway and the subnet that hosts for example a vsi that wants to communicate over the vpn gateway connection. Both are VPC subnets but different ones.

**Comment by austinmama** [comment]
Topic updated by Development team here: https://cloud.ibm.com/docs/vpc?topic=vpc-acls-security-groups-vpn
