### ISSUE TITLE
IP range not defined by attached subnet

### ISSUE THREAD

**Issue by joergrenn** [ibm-cloud-docs/vpc#51]
The article states that:
- for inbound rules, ... The destination IP range is determined by the attached subnet.
- With outbound rules, ... The source IP range is determined by the attached subnet.

This is not correct.
Of course only attached subnets are influenced by the ACL, but the source and destination ranges are not limited to the attached subnet.
. For example a subnet containing a VPN Gateway, in this case traffic from the tunnel needs to be routed from the tunnel into the VPN subnet and from there to another VPC subnet. 
In this case the rules are soure IP range: On-premises subnet IP range and destination IP range: VPC subnet
And the VPC subnet is not an attached subnet.
Please correct the description on the page.
thanks.

**Comment by austinmama** [comment]
waiting on response from Development

**Comment by mark19830206** [comment]
@austinmama I am not sure this issue is talking about table 1 or 2? I suppose it is table 2. But I still not understand what mean the attached subnet.

**Comment by joergrenn** [comment]
@mark19830206 it is not talking neither of the tables.  
It is talking about that the statements that I have listed are wrong.

**Comment by austinmama** [comment]
Statements are being removed.  Thank you.
