### ISSUE TITLE
The limitations for virtual private endpoints needs to be updated (Direct Link 2.0 is supported)

### ISSUE THREAD

**Issue by strattner** [ibm-cloud-docs/vpc#53]
Reference page: https://cloud.ibm.com/docs/vpc?topic=vpc-limitations-vpe (updated October 30th 2020)

It says that VPEs are not supported for access with IBM Cloud Direct Link (2.0)

According to this: https://cloud.ibm.com/docs/dl?topic=dl-vpe-for-ibm-cloud-direct-link (updated May 28th 2021) it is supported, for Dallas and Washington at least.

**Comment by austinmama** [comment]
@strattner 

 VPE for VPC is currently only accessible from VPC and not from Direct Link or TGW.
