### ISSUE TITLE
How to access service endpoints via vpn

### ISSUE THREAD

**Issue by joergrenn** [ibm-cloud-docs/vpc#55]
Hello,
please update step 2 and add a decription how what needs to be configured.

> For the VPN connection, make sure that the local subnets include the range...
According to IBM support (ref CS2363429) this is referring to traffic selectors for policy based vpns.
This is not clear from the description.
What about a route based VPN? How can a route based vpn be configured to allow access to the service endpoints trough VPN?
thanks

**Comment by austinmama** [comment]
Thank you for your feedback.  Please review updates to your issue at:

https://cloud.ibm.com/docs/vpc?topic=vpc-build-se-connectivity-using-vpn
