### ISSUE TITLE
Placement group documentation in prod points to Staging resources

### ISSUE THREAD

**Issue by tommyk-enablement** [ibm-cloud-docs/vpc#56]
In the Placement group documentation for the Beta, for the Quota links, they are pointing to the Staging version of the documentation. 
https://cloud.ibm.com/docs/vpc?topic=vpc-about-placement-groups-for-vpc#beta-limitation

**Comment by gudrun-wolfgram** [comment]
Thanks, Tommy. The quotas link is updated now.
