### ISSUE TITLE
EventStream Enterprise is supported in VPE but not mentioned in documentation

### ISSUE THREAD

**Issue by ahmadsayed** [ibm-cloud-docs/vpc#57]
in the VPC vpe supported services, Eventstream Enterprise is not mentioned meanwhile it works
https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services

**Comment by austinmama** [comment]
Thank you for your feedback. "Event Streams for IBM Cloud" has been added to the list.
