### ISSUE TITLE
Correct note regarding route based VPN

### ISSUE THREAD

**Issue by joergrenn** [ibm-cloud-docs/vpc#58]
In the section: https://cloud.ibm.com/docs/vpc?topic=vpc-using-vpn#vpn-getting-started
there is the note:

> VPN for VPC supports only one route-based VPN per zone per VPC.

according to IBM support case: CS2369731 this is not correct:
> You can have more than one route-based connection to the same VPC zone and two different on-premise networks.  Here is the statement confirming that from the documentation - see Use Case #2:
https://cloud.ibm.com/docs/vpc?topic=vpc-using-vpn#use-case-2-vpn-connections-to-multiple-remote-peer-devices

please adapt the documentation as appropriate

**Comment by austinmama** [comment]
@joergrenn   Thank you for your feedback. Development responded stating that "One statement is for VPN gateway and the other is for a VPN connection. The statements are correct as is."  If you have any further questions, please contact me on Slack or email at dliburdi@us.ibm.com.
