### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/vpc#59]
https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-vpc-encryption

Team, there is an error in documentation. It refers to a Table 1 which is not in the doc. https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-vpc-encryption. Could anyone manage to modify it? ... Thanks.

**Comment by donslovenkai** [comment]
Fixed. Added Table 1.

**Comment by donslovenkai** [comment]
Fixed file, added Table 1.
