### ISSUE TITLE
Text error

### ISSUE THREAD

**Issue by francesca-gigante** [ibm-cloud-docs/vpc#6]
The following text (-f "user_ID") has an error because the command is -C "user_ID" as stated in the previous statements.

If you are using OpenSSH version 7.8 or higher and plan to to access a Windows instance, use the following command to generate the key in PEM format. $ssh-keygen -m PEM -t rsa -f "user_ID"

**Comment by gudrun-wolfgram** [comment]
@francesca-gigante Thank you for the feedback. The keygen command for Windows has been updated to use the -C parameter.
