### ISSUE TITLE
Is expandable volumes truly GA available?

### ISSUE THREAD

**Issue by tommyk-enablement** [ibm-cloud-docs/vpc#61]
To confirm, is expandable volumes really GA? 
The feature flags don't seem to be all turned on and I checked during the release planning call that it should not be GA'd yet? 

https://cloud.ibm.com/docs/vpc?topic=vpc-expanding-block-storage-volumes

**Comment by tommyk-enablement** [comment]
This is about the release notes mention: 
https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes

**Comment by donslovenkai** [comment]
Investigating with the dev lead and release manager.

**Comment by vickmuir** [comment]
The issue is outdated. Block Storage capacity expansion is GA.
