### ISSUE TITLE
Hyper Protect Crypto Services - Root key rotation (link broken)

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/vpc#63]
Hyper Protect Crypto Services - Root key rotation (link broken)

**Comment by austinmama** [comment]
metadata also broken (see top of page). https://cloud.ibm.com/docs/vpc?topic=vpc-vpc-key-rotation&interface=ui

**Comment by vickmuir** [comment]
Root key rotation links work now.
