### ISSUE TITLE
Incomplete IAAS endpoint list

### ISSUE THREAD

**Issue by soumypau1** [ibm-cloud-docs/vpc#64]
Hi Team, 
Per this link, we need to allow outgoing traffic to port 53,80 and 443 to 161.26.0.0/16 at a minimum for VMs to come up in a VPC. 

https://cloud.ibm.com/docs/vpc?topic=vpc-service-endpoints-for-vpc#cloud-service-endpoints

However, Linux VMs fail to come up unless we open port 8443 to 161.26.0.0/16

Please update the document to reflect the same

**Comment by austinmama** [comment]
@sheltons

**Comment by austinmama** [comment]
@sheltons  for your attention

**Comment by sheltons** [comment]
Page updated. Closing.
