### ISSUE TITLE
Can not find the roles described in BM documentation to add to account

### ISSUE THREAD

**Issue by tommyk-enablement** [ibm-cloud-docs/vpc#68]
In the documentation we are asked to add roles to Bare Metal Console Administrator to access the ESXi Direct Console User Interface (DCUI) and Bare Metal Advanced Network Operator but during the Beta, these roles are not available. 

Can you please check if these roles are needed and why they do not appear to be available for adding to accounts?

**Comment by vickmuir** [comment]
It looks like the discrepancy has been resolved as the roles that are mentioned in the topics can also be seen in the console.

![Screenshot 2023-10-24 at 10 36 29 AM](https://github.com/ibm-cloud-docs/vpc/assets/28069378/a1926369-40f9-470f-b3bc-f25784910823)
