### ISSUE TITLE
Isuue while using an ssh key created in Windows

### ISSUE THREAD

**Issue by francesca-gigante** [ibm-cloud-docs/vpc#7]
In Windows:

using "ssh-keygen -m PEM" seems not producing a good private key because the "ibmcloud is instance-initialization-values" command fails saying that the key has not a valid PEM format
 
using the PuTTYgen ssh key seems not producing a good public key because it fails the parsing during VSI creation

**Comment by gudrun-wolfgram** [comment]
@francesca-gigante were you able to get connected to the Windows VSI? 

It sounds like you tried creating keys using both the OpenSSH method and the PuTTYgen method? 

When you copied the public key before creating the virtual server instance, did you include the ssh-rsa at the beginning of the key file? When I tried copying my public key into the UI without the _ssh-rsa_ part, I received an error message. When I included ssh-rsa, the SSH key loaded fine into the UI. 

If that doesn't resolve the issue, you might want to double-check this tip also: "When you copy an SSH key from a terminal to add the key to your VPC, sometimes extra line breaks are introduced which cause a parsing error. To avoid this issue, first paste your SSH key into a text editor and remove any extra line breaks. Then, copy the SSH key from text editor and paste it into the VPC UI, CLI, or API." 

The line breaks could potentially cause the PEM format error when you are using the ibmcloud is instance-initialization-values command.
