### ISSUE TITLE
Incorrect role names in doc

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/vpc#70]
This doc mentions role names that don't exist or are not named as expected.

https://cloud.ibm.com/docs/vpc?topic=vpc-planning-for-bare-metal-servers
<img width="993" alt="Screen Shot 2021-08-25 at 9 03 43 AM" src="https://user-images.githubusercontent.com/11874942/130797640-5fbd53c4-efdf-4d19-b990-a1fef19e21d5.png">

the role names in IAM do not start with **Bare Metal**

**Comment by vickmuir** [comment]
It looks like the discrepancy has been resolved as the roles that are mentioned in the topics can also be seen in the console.

![Screenshot 2023-10-24 at 10 36 29 AM](https://github.com/ibm-cloud-docs/vpc/assets/28069378/57de5c6d-a6d5-48b9-a8e3-81e6c485b10d)
