### ISSUE TITLE
Can this doc be updated 

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/vpc#71]
It does not make sense to have such a message and the doc has not been updated since July 20th

![image](https://user-images.githubusercontent.com/11874942/130973813-6ba002ff-84da-4c18-b02d-f9c27ca3a949.png)

**Comment by gudrun-wolfgram** [comment]
Thanks, Dimitri. This issue has been resolved in the current version of the doc: https://cloud.ibm.com/docs/vpc?topic=vpc-connect-to-ESXi-bare-metal-servers
