### ISSUE TITLE
GPUs in VPC are STILL IN BETA and need to be noted as such 

### ISSUE THREAD

**Issue by AliseATX** [ibm-cloud-docs/vpc#72]
The GPU family of profiles and details of the profiles should ALL be clearly marked as being in BETA and only available through a sales Rep.  This is a CLOSED allow listed beta. 

This is urgent.

**Comment by austinmama** [comment]
@AliseATX  I understand that you worked with @keith-merchant-ibm on this issue.  Closing.  If you have any further issues, please contact Keith.  Thank you for your feedback.
