### ISSUE TITLE
VPC Dedicated Billing option.

### ISSUE THREAD

**Issue by Sivasaivm** [ibm-cloud-docs/vpc#74]
Hello,
Under following documentation https://cloud.ibm.com/docs/vpc?topic=vpc-bare-metal-server-faq&interface=ui#billing-options . Could you tell us the billing model as Hourly or monthly etc? The current explanation is not clear.

**Comment by amatetic** [comment]
Thank you for your feedback. I have created a jira item to track this issue.

**Comment by jmilst** [comment]
Hi @Sivasaivm - According to the [documentation](https://cloud.ibm.com/docs/vpc?topic=vpc-about-bare-metal-servers#bare-metal-pricing-options), Bare Metal Servers on VPC are hourly, pay-as-you-go. While many of the add-ons are billed monthly. You can find more information about pricing [here](https://www.ibm.com/cloud/bare-metal-servers/pricing).
