### ISSUE TITLE
Table is messed up

### ISSUE THREAD

**Issue by netapp-bcammett** [ibm-cloud-docs/vpc#77]
https://cloud.ibm.com/docs/vpc?topic=vpc-user-access-to-dedicated-hosts-and-groups

Go to step 3 under "Creating a virtual server instance and block storage volume"

**Comment by amatetic** [comment]
Thank you for your feedback. I have created a JIra item to track this issue.

**Comment by vickmuir** [comment]
This issue can be closed, the table formatting has been corrected a while ago.
