### ISSUE TITLE
Link to API in 'next steps' takes you to correct page but UI subtab

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vpc#78]
In the Next Steps section the link for 'Adjusting total volume bandwidth from the API.' on page https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-bandwidth&interface=ui links to https://cloud.ibm.com/docs/vpc?topic=vpc-managing-virtual-server-instances&interface=ui#adjusting-bandwidth-allocation-api

But should in fact be https://cloud.ibm.com/docs/vpc?topic=vpc-managing-virtual-server-instances&interface=api#adjusting-bandwidth-allocation-api

**Comment by amatetic** [comment]
Thank you for your feedback - I have created a Jira item for us to track and complete this issue.
