### ISSUE TITLE
Block storage performance page does not give all block sizes

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vpc#79]
Page https://cloud.ibm.com/docs/vpc?topic=vpc-capacity-performance&interface=api details Block Storage Capacity and Performance. It mentions that the Tiered block storage volumes have block sizes of either 16Kb or 256Kb. It does not mention what the blocksize is for the Custom tier which I think is 128Kb?

**Comment by amatetic** [comment]
Thank you for this feedback. I have created a Jira item to track this issue and it is assigned to the writer working on Block Storage. https://jiracloud.swg.usma.ibm.com:8443/browse/CFD-3531

**Comment by vickmuir** [comment]
The topic in question has been updated a while ago. The Custom profile has 256 KB block-size.
