### ISSUE TITLE
About Security Groups restriction.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#80]
Hi,

https://cloud.ibm.com/docs/vpc?topic=vpc-limitations&locale=en#network-restrictions
> A security group can be configured in a single zone only.
> A security group can’t reference another security group in a different zone in the same region.

I think this restriction is not correct.
Security Groups don't have a concept of "zone" and can be applied to servers in multiple zones.

Thank you,

**Comment by austinmama** [comment]
@sheltons  Lauren is following up w/ ACL SME to ensure this is correct in the documentation.

**Comment by Lauren-Fulcher** [comment]
Checked in wit Quan Do 8/22/22 - he said it is correct that "Security Groups don't have a concept of 'zone' and can be applied to servers in multiple zones" and the documentation needs to be updated. Editing this topic now: https://cloud.ibm.com/docs/vpc?topic=vpc-limitations&locale=en#network-restrictions

**Comment by Lauren-Fulcher** [comment]
Updated in staging and prod, closing 8/23/22
