### ISSUE TITLE
The description of Service Endpoint should be modified.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vpc#82]
Hello,

https://cloud.ibm.com/docs/vpc?topic=vpc-service-endpoints-for-vpc&locale=en#cloud-service-endpoints
> These endpoints are available through DNS (Domain Name System) names in the cloud.ibm.com domain and resolve to 166.8.x.x addresses.

The above description of "166.8.x.x" is vague and misleading. People reading this will think it is "166.8.0.0/16".
In fact, it is "166.8.0.0/14". The following is an accurate description and I think it should be the same.
https://cloud.ibm.com/docs/vpc?topic=vpc-build-se-connectivity-using-vpn&locale=en

Thank you,

**Comment by sheltons** [comment]
Content is already updated. Closing.
