### ISSUE TITLE
Format error in documentation

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/vpc#83]
There is a significant format error in the page ... it goes from just after paragraph "For example, if you want to create a VPE for IAM, you can make the following REST API call from an on-premises network by using a private VPC API endpoint to provision VPE for IBM Cloud Identity and Access Management (IAM)." ... up to EOD. Could you please fix it? Thanks.

https://cloud.ibm.com/docs/vpc?topic=vpc-end-to-end-private-connectivity&interface=api&locale=en

**Comment by gudrun-wolfgram** [comment]
Made initial adjustments for marked-it 2.0 requirements.

**Comment by austinmama** [comment]
Verified. Closing.
