### ISSUE TITLE
doc uses us-south-2 which is on a different VSI and causes an error

### ISSUE THREAD

**Issue by jdriver2** [ibm-cloud-docs/vpc#84]
Also the command: 
ibmcloud is images | grep -i "debian.*available.*amd64.*public" | cut -d" " -f1

returns multiple lines causing that step to FAIL

additionally, at the end would be good to have more description about:
169.61.161.150 mykey
Such as what does that IP address represent, and where did mykey come from? mykey is not created in the earlier steps of the tutorial so leaves some questions.

**Comment by austinmama** [comment]
https://test.cloud.ibm.com/docs/vpc?topic=vpc-creating-a-vpc-using-cli#select-a-profile-and-image-for-the-instance

**Using the CLI to create VPC resources** topic

**Comment by vickmuir** [comment]
Thank you for the feedback.
1. Looking at the topic, the only mention of us-south-2 is in the public gateway section, we have to change that to match everything else in us-south-3.
2. The command `ibmcloud is images | grep -i "debian.*available.*amd64.*public" | cut -d" " -f1` needs to change to something like `ibmcloud is images | grep -i "ibm-debian-12-0-minimal-amd64-1" | cut -d" " -f1` to return one result.
3. We need to add more information regarding peer address and pre-shared key from https://test.cloud.ibm.com/docs/vpc?topic=vpc-vpn-adding-connections.
