### ISSUE TITLE
Authorize resources of type Flow Logs for VPC 

### ISSUE THREAD

**Issue by martyg1987** [ibm-cloud-docs/vpc#85]
Hi there. 

I've spotted some updated text that might confuse people under this section on the page "Authorize resources of type Flow Logs for VPC "

Where it says "**Select Services based on attributes**." In the portal is shows **"Resources based on selected attributes**" 

its the same for Source and target service.

Mg

**Comment by austinmama** [comment]
Issue was never closed, but fixed. Thank you for letting us know.
