### ISSUE TITLE
Typos in documentation for VPC block storage

### ISSUE THREAD

**Issue by lefurgy** [ibm-cloud-docs/vpc#86]
On this webpage: https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-about
"volume" is misspelled as "volune" in link text.

On this webpage: https://cloud.ibm.com/docs/vpc?topic=vpc-capacity-performance
"IOPS is are based" should be "IOPS is based"

**Comment by donslovenkai** [comment]
Fixed and published.
