### ISSUE TITLE
Bare Metal VPC responsibilities

### ISSUE THREAD

**Issue by iknowango** [ibm-cloud-docs/vpc#88]
The responsibilities table does not match on the Bare Metal VPC topic what is shared on the Overview topic for a similar table of responsibilities. All columns should be shared for bare metal in the VPC document.

Bare Metal VPC: https://cloud.ibm.com/docs/vpc?topic=vpc-responsibilities-vpc#overview-by-resource
Overview: https://cloud.ibm.com/docs/overview/terms-of-use?topic=overview-shared-responsibilities#iaas-services-responsibilities

**Comment by l2fprod** [comment]
@austinmama @jmilst 

when are the changes going to be made so https://github.ibm.com/vpc-baremetal/ServiceFramework/issues/113 can be closed?

**Comment by iknowango** [comment]
Opened request internally.
