### ISSUE TITLE
IBMCLOUD cli command not working

### ISSUE THREAD

**Issue by AnandPalani92** [ibm-cloud-docs/vpc#9]
As per the [Documentation](https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_windows), I have just executed few command on via ibmcloud cli. I got following error

` ibmcloud is instance 0737_31190e9213213123      

FAILED
'is' is not a registered command. See 'ibmcloud help'.

`
I have used following ibmcloud cli version.

`ibmcloud -v
ibmcloud version 1.2.1+54b1b5e-2020-09-04T03:46:01+00:00`

**Comment by gudrun-wolfgram** [comment]
@AnandPalani92 - Thank you for your feedback. It looks like the infrastructure-service plug-in is not installed. The Connecting topic is now updated to highlight this requirement. 

Connecting to Windows instances
https://cloud.ibm.com/docs/vpc?topic=vpc-vsi_is_connecting_windows

This is the new section:

> Ensure that you downloaded, installed, and initialized the following CLI plug-ins:
> 
>    IBM Cloud CLI
>    The infrastructure-service plug-in
>      For more information, see Setting up your API and CLI environment.

Setting up your API and CLI environment
https://cloud.ibm.com/docs/vpc?topic=vpc-set-up-environment#cli-prerequisites-setup
