### ISSUE TITLE
What is the name for VPC Infrastructure Services

### ISSUE THREAD

**Issue by SaloniRathi** [ibm-cloud-docs/vpc#90]
I want to create an access policy for VPC Infrastructure Services using terraform. I cannot find the service name for VPC Infrastructure Services.

**Comment by amatetic** [comment]
@SaloniRathi thank you for your feedback. We will take a closer look at your comments in upcoming sprints.

**Comment by amatetic** [comment]
@SaloniRathi I have talked with development. Here is the link to the terraform information on IAM service policy:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/iam_service_policy

Please let me know if this answers your question. I can review where to best call this link out in our documentation.

**Comment by amatetic** [comment]
No further questions on this issue - closing item
