### ISSUE TITLE
mount VPC File Share on Windows Server

### ISSUE THREAD

**Issue by joergrenn** [ibm-cloud-docs/vpc#91]
Please provide instructions on how to mount a VPC FileShare NFS on Windows Server.
Instructions how to mount on linux are available:
https://cloud.ibm.com/docs/vpc?topic=vpc-file-storage-mount-centos&interface=ui

**Comment by amatetic** [comment]
@joergrenn Thank you for your feedback. We will take a closer look at your comments in upcoming sprints.

**Comment by vickmuir** [comment]
The VPC File product in general does not support Windows hosts as Windows does not currently have an NFS v4.1 client.

**Comment by joergrenn** [comment]
@vickmuir 
> The VPC File product in general does not support Windows hosts as Windows does not currently have an NFS v4.1 client

That it does not work on windows is also an Information that would in my opinion be valuable to have in the documentation.
So instead of describing only how it works on the supported Operating systems I would be great to also add a Note about the Operating Systems not supported. Or list the preconditions needed to use VPC file shares.
