### ISSUE TITLE
Add Watson Services to List of Services that Support VPE 

### ISSUE THREAD

**Issue by alannatodd** [ibm-cloud-docs/vpc#94]
Some Watson services now support Virtual Private Endpoints - Watson Assistant, Watson Discovery, and Watson Speech to Text and Text to Speech. 

Could you add them to the list of supported services along with this set of instructions: https://cloud.ibm.com/docs/watson?topic=watson-virtual-private-endpoints

Thanks!

**Comment by DLM-IBM** [comment]
Added 4 Watson services to the list in these topics: 
https://test.cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services
https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services
