### ISSUE TITLE
Outdated list of Direct Endpoints to COS

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/vpc#95]
The list that is available here: 
https://cloud.ibm.com/docs/vpc?topic=vpc-connecting-vpc-cos#regional-endpoints

has fallen behind from the availability of Direct Endpoints in other regions as seen under the Direct tab here: 
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-endpoints#endpoints-region

**Comment by amatetic** [comment]
@dprosper thank you for your feedback. I have updated the content and it is now available. https://cloud.ibm.com/docs/vpc?topic=vpc-connecting-vpc-cos#regional-endpoints

**Comment by dprosper** [comment]
@amatetic Thank you for taking care of this update, looks good.
