### ISSUE TITLE
Broken Link VPE for VPC infrastructure resources for Terraform

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/vpc#96]
The link `VPE for VPC infrastructure resources for Terraform` in the section **Related Links** of the page [About virtual private endpoint gateways](https://cloud.ibm.com/docs/vpc?topic=vpc-about-vpe) is broken

**Comment by amatetic** [comment]
@lionelmace thank you for your feedback. The broken link issue is resolve and live on the production build.
