### ISSUE TITLE
Quota for Dedicated Host Groups is not documented

### ISSUE THREAD

**Issue by eniopineda** [ibm-cloud-docs/vpc#97]
There is a quota/limit enforced for Dedicated Host Groups per region per account, but that limit is not documented in the Quotas and service limits (https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#vpcquotas) nor the documentation for Dedicated Hosts.

Limits and quotas are OK but they need to be documented.
There is an error message indicating the quota has been hit, but there is no documentation anywhere stating what the quota is.

```
04:39:02 ERROR: Request  POST :  /v1/dedicated_hosts?version=2022-01-20&generation=2  response status_code:  400  res: <Response [400]>
04:39:02     *** over_quota -- Allocating a dedicated group will put user over quota. Allocated: 100, Quota: 100 
```

**Comment by gudrun-wolfgram** [comment]
@eniopineda - Thanks for your feedback. In the topic that you identified, please see the Compute resources section, https://cloud.ibm.com/docs/vpc?topic=vpc-quotas#vsi-quotas. 

> When you provision virtual server instances and dedicated hosts, the vCPU associated with these resources counts toward the vCPU quotas per region. Instances that are provisioned on dedicated hosts do not count against the vCPU quota.

**Comment by eniopineda** [comment]
@gudrun-wolfgram I wasn't asking about vCPUs nor dedicated hosts. I understand how those quotas work.
I was specifically asking about **Dedicated Host Groups**. The link you include does not mention anything about **Dedicated Host Groups**.
