### ISSUE TITLE
doesn't IBM VSIs support s390 and power VSIs now?

### ISSUE THREAD

**Issue by matsakis** [ibm-cloud-docs/vpc#98]
this page states that VSIs are x86 only but can't you get a Power or s390 (linuxone) VSI these days? It should be updated as it is misleading. For example, like what's on this page: https://cloud.ibm.com/docs/vpc?topic=vpc-about-images 
thanks

**Comment by gudrun-wolfgram** [comment]
@matsakis - Further down on the page you noted, the LinuxONE (s390) OSes are listed: 

**Supported LinuxONE (s390x processor architecture) stock image operating systems**
https://cloud.ibm.com/docs/vpc?topic=vpc-about-images#s390x-supported-os

Power Systems Virtual Servers are created outside of VPC infrastructure. The Power Systems Virtual Servers information is below. Thanks. 

Getting started with IBM Power Systems Virtual Servers
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started
