### ISSUE TITLE
Block storage quota has a specific explanation on how to increase quota which is not needed

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-docs/vpc#99]
It shows this sentence:

![image](https://user-images.githubusercontent.com/12746550/151608161-bfb57d55-5edc-4a66-9b2a-f8f1ce984eda.png)

where the text at the top is enough and applies to all VPC quota

![image](https://user-images.githubusercontent.com/12746550/151608230-b05db7b8-1b6b-48d3-b0dc-291766164b5d.png)

**Comment by amatetic** [comment]
Thank you for your feedback @l2fprod I have made the above update and it should be visible in the production content.
